### ISSUE TITLE
Add 'share feedback' contribution section

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#1000]
# What

If we add links for the different types of contribution in the context of use Eg: add a link for proposing new components or suggesting a change to one to the navigation where users are looking for components.

Then users will more likely see that they can contribute

# We know this works;
- When we see people easily accessing our contribution process via our website pages. 
- We can do this via a usability test - see if people can find where to contribute 
- We can monitor the analytics - number of in-page clicks

# Task list
- [x] Map all the different types of contribution
- [x] Map current service manual pages (annotate with page stats, research insights and highlight current links to contribution)
- [x] Identify areas on the service manual pages for potential links to contribution
- [x] Write design hypotheses for propose changes
- [x] Sketch ideas
- [x] Prototype ideas
- [ ] Test ideas - I've set this up as a separate issue https://github.com/nhsuk/nhsuk-service-manual/issues/1115

# Sub-task
- [x] @sarawilcox to review and test new content contextual link with content designers
- [x] @Tosin-Balogun and @davidhunter08 to create issues for content guide pages
- [x] @sarawilcox to cross link issues in content backlog to service manual content pages

# Related
EPIC: Improve Service Manual website contribution user experience #993 
Sibling: #1001 Hypothesis: Add share buttons

**Comment by davidhunter08** [comment]
## Insight

From @sarawilcox 

> Have just seen an instance of someone getting confused when they wanted to contribute.
> 
> - They wanted to amend a partial in the accessibility guidance: https://service-manual.nhs.uk/accessibility/content.
> - Went to the community section and this page: https://service-manual.nhs.uk/community/propose-component-pattern
> - Started to raise an issue using the new issues template: https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/new
> - Got confused and contacted me.

**Comment by lucyha** [comment]
As part of our review of the accessibility pages @AJSMITH1512 identified that the information under 'Share your research' in the 'Accessibility guidance for user research' section ([linked here](https://service-manual.nhs.uk/accessibility/user-research)) should include more detailed information on how to contribute to the service manual in the context of user research and accessibility.

**Comment by Tosin-Balogun** [comment]
# Service manual page analytics - Feb 2021

**Note:** These stats only include the number of users who accept cookies.

### Top 5 visited pages:
1. /design-system - 2,592 (11.85%)
2. /home - 1,727 (7.90%)
3. /design-system/components - 1,364 (6.24%)
4. /design-system/styles - 879 (4.02%)
5. /service-standard - 878 (4.02%)

### Top 5 landing pages:
1. /home - 982 (18.21%)
2. /design-system - 731 (13.56%)
3. /content/inclusive-language - 352 (6.53%)
4. /service-standard - 280 (5.19%)
5. /content - 219 (4.06%)
---
[ga-service-manual-2021-feb__landing-pages.pdf](https://github.com/nhsuk/nhsuk-service-manual/files/6082412/ga-service-manual-2021-feb__landing-pages.pdf)
[ga-service-manual-2021-feb__total-page-visits.pdf](https://github.com/nhsuk/nhsuk-service-manual/files/6082413/ga-service-manual-2021-feb__total-page-visits.pdf)

**Comment by amyj2110** [comment]
[First click test preview](https://778p6776.optimalworkshop.com/chalkmark/kou574ke)

**Comment by Tosin-Balogun** [comment]
> [First click test preview](https://778p6776.optimalworkshop.com/chalkmark/kou574ke)

Looks great @amyj2110 - I wonder if we can send this both within and outside NHSD

**Comment by Tosin-Balogun** [comment]
# Share your findings button
## Methodology @amyj2110 

People were asked to complete a first click test on Optimal Workshop. They were given the following task to complete:

>During some user research, you found that the breadcrumbs didn't really work well. You want to share this insight with the service manual to try to change the way breadcrumbs are presented. Where would you click to do this?

They were asked to complete this task twice, but shown different screens each time. The task order was randomised to reduce order effects.

## Results

 
<img width="1260" alt="Screenshot 2021-03-23 at 17 14 48" src="https://user-images.githubusercontent.com/71393402/112188872-4ffd8900-8bfb-11eb-9df0-09811e693a85.png">


The image on the left shows the variation 1 screen, showing a "Have you tested this pattern?" section, with a "Share your findings" button, on the left hand side, under the side navigation.

The image on the right shows the variation 2 screen, showing a "Have you tested this pattern?" section, with a "Share your findings" button, at the bottom of the main page.

### Variation 1

78% of people successfully clicked either the "Share your findings" button or the "get in touch to share your research findings" link.

- 9% clicked the "Share your findings" button
- 69% clicked the "get in touch to share your research findings" link

#### Other places people clicked included:

- 6% clicked the "Community and contribution" link in the main top navigation
- 10% clicked the "get in touch" link at the bottom of the page

People took 13.2 seconds on average to do their first click.

### Variation 2

82% of people successfully clicked either the "Share your findings" button or the "get in touch to share your research findings" link.

- 58% clicked the "Share your findings" button
- 24% clicked the "get in touch to share your research findings" link

##### Other places people clicked included:

- 6% clicked the "Community and contribution" link in the main top navigation
- 3% clicked the "Component" link in the breadcrumbs navigation
- 9% clicked the "get in touch" link at the bottom of the page

People took 12.7 seconds on average to do their first click.

## Recommendations
- Variation 2 had a higher proportion of people clicking on the "Share your findings" button.  This shows that it was probably a more obvious for people to click compared to the side button in variation 1.
100% of people who had not used the service manual before clicked the "Share your findings" button in both variations.
**Having navigation and CTAs within the page is better than having them in the side navigation.**
- The page tested was quite short, and both "Share your findings" button and "get in touch to share your research findings" link were quite close together. It would be good to see where people might click if these two sections are more separated.
**Understand where people might click if the two feedback links are separated.**
- People are still clicking the generic "get in touch" link at the bottom of the page. We should look to repurpose this link, or make a more obvious distinction between "get in touch" and contributions areas.
**Investigate how to distinguish between "get in touch" and allowing people to make contributions.**

**Comment by Tosin-Balogun** [comment]
# Hypotheses
- If we changed the contribution prompt to be a question begging an answer, people would feel invited and encouraged to enter the contribution process. We know this works if we see an increase in people starting a contribution from this prompt
- If we set expectations of GitHub being part of the contribution journey, a user would feel encouraged to continue the contribution. We know this works, if we hear people tell us it helped them make a GitHub account or we see new commenters on existing issues
- If we replace the hyperlink to contribution with an action link so it stands out more, people will see the call to action more easily. We know this works if we see an increase in people starting a contribution from this link

**Comment by sarawilcox** [comment]
### Quick test of content partial with 3 content designers
(I'm starting the write-up now. Will have to finish it later.)

#### Recommended rewording
> Would you like to contribute this guidance?
> Please let us know how this has worked for you and, in particular, if you have research findings, such as user research or desk research, to share. This will help us improve it for everyone.
> 
> Before you start, you will need a GitHub account. It's an open forum where we collect feedback.
> 
> Share your research findings on GitHub
> If you have any questions, you can message us on Slack. You will need to set up a Slack account if you do not have one. Or you can contact us by email.

#### Notes
They recommended making Slack the default, so that we have conversations there, and letting people know that they will need a Slack account. Email then becomes the alternative if people don't have Slack.

They wanted to know what sort of research. Desk and user research, for example.

Can product leads make sure that key findings from a mission/project are written up in the style guide/design system. (That came up in our contribution research.)

Could this all go in a "call out box". That might make it easier for people to recognise that it appears at the bottom of every page that it's a standard thing. 

@davidhunter08 @Tosin-Balogun, what do you think?

**Comment by sarawilcox** [comment]
Note too that they thought at first that this was more like a satisfaction survey? "Did you find this page useful?" in the sense of "Did you find what you wanted on this page?" When we talked about it and made it clear that this is about contribution, they suggested the wording above.

Also, where we currently say, "Have you used this guidance?", they felt that was a bit odd as they are on the guidance page, so of course, they've used the guidance.

**Comment by Tosin-Balogun** [comment]
Thanks for sharing the result of the test @sarawilcox - I have made some alterations to the partial based on that. I'd look at including the first paragraph change. 

>in particular, if you have research findings, such as user research or desk research, to share. 

Is it important we distinguish the kind of research we are asking for or does research cover all of it?

<img width="520" alt="Screenshot 2021-03-31 at 17 01 46" src="https://user-images.githubusercontent.com/71393402/113174977-d725af00-9242-11eb-8d0c-2ffcccf284f6.png">

**Comment by sarawilcox** [comment]
We originally just said research but the feedback was, what sort of research. They asked us to specify desk research and user research.

**Comment by sarawilcox** [comment]
Also I think we need to keep the service manual team email but make Slack the default. The content designers yesterday thought that people might need to contact us for help getting onto Slack, for example, so I don't think we can just route emails through to the Accessibility Working Group or to NHSX.

**Comment by davidhunter08** [comment]
Related to https://github.com/nhsuk/nhsuk-service-manual/issues/1001
