### ISSUE TITLE
EPIC: Content Style Council (Monthly)

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#1017]
## What

Facilitate a design system meet-up.

## Why

We need to engage with the community to give updates and get feedback on components and patterns in development.

## When

Every 4 weeks

## Where

Content Style Council (remotely via Microsoft Teams).

## How

1. 5 hour meeting facilitated by the content community and service manual team with content style guide updates, content crits and open discussion.

Session notes and outcomes are stored in SharePoint.

## Desired outcomes

1. Actionable feedback for iterating and improving the Content Style Guide

## To do

- [x] [Prepare for January Content Style Council meeting #792](https://github.com/nhsuk/nhsuk-service-manual/issues/792)
- [ ] [Prepare for March Content Style Council meeting #79](https://github.com/nhsuk/nhsuk-service-manual/issues/793)
- [ ] Prepare for April Content Style Council meeting
- [ ] Prepare for May Content Style Council meeting
- [ ] Prepare for June Content Style Council meeting
- [ ] Prepare for July Content Style Council meeting
- [ ] Prepare for August Content Style Council meeting
- [ ] Prepare for September Content Style Council meeting
- [ ] Prepare for October Content Style Council meeting
- [ ] Prepare for November Content Style Council meeting
- [ ] Prepare for December Content Style Council meeting
