### ISSUE TITLE
Discuss prototypes for testing content scenarios

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1030]
I think we now have some good examples to look at across these 4 scenarios:
- [x] [components and headings](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/301)
- [x] the [inset text issue](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/18)
- [x] [hint text](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/17)
- [x] [hyphens or spaces](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/206)

### Task
Get together and review the examples and decide what we want to prototype
