### ISSUE TITLE
Present contribution work to the community

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#1047]
# What
We need to give an update to the community about the progress we have made since the rounds of user research we did
# Why
It is important to give the community visibility of where things are, as well as use it as a path allow them to engage with us. We think there is an opportunity to check appetite for co-design sessions here
# Task list
- [x] Make presentation structure
- [x] Put together a slide deck
- [x] Review slide deck with team
- [x] Present
# Related
#685 #983
