### ISSUE TITLE
EPIC: Prototype kit improvements (Discovery)

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1062]
## What

There is a need to continual develop the prototype kit to ensure it is in line with the latest development practices. This EPIC is to allow some concentrated effort to review improvements for the prototype kit.

## Why

Without continuous development the prototype will lose its value as a critical resource for designers and developers.

## Must

- [ ] Review the prototype and identify areas for improvement
- [ ] Review the backlog for issues relating to the prototype
- [ ] Develop a list of improvements that can be used for prioritisation
- [ ] Prioritise the list of improvements

**Comment by Indu-Kaila** [comment]
Will need to list the relevant improvements needed to the prototype kit in this issue ie 1062 the findings that arise from the completion of the upcoming user research/testing sessions on the prototype kit
