### ISSUE TITLE
Present contribution work to the community at content huddle

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#1084]
# What
We need to give an update to the community about the progress we have made since the rounds of user research we did
# Why
It is important to give the community visibility of where things are, as well as use it as a path allow them to engage with us. We think there is an opportunity to check appetite for co-design sessions here
# Task list
- [x] Make presentation structure
- [x] Put together a slide deck
- [x] Review slide deck with team
- [ ] Present
# Related
#685 #983

**Comment by sarawilcox** [comment]
Hi @Tosin-Balogun, the next content huddle is likely to be in a months' time but we could potentially arrange something earlier. What would you prefer?

Also, if you could ping me your slides, I'll have a look at them from the point of view of the content style community. They might benefit from a bit more intro than you had for the design community and a few content tweaks so content designers can focus on what you're saying rather than how you've capitalised or punctuated your slides ;-)

**Comment by henocookie** [comment]
Happy to do something earlier so we can update the content community whilst the latest work Tosin can share details about is as fresh as possible 😀. Happy to wait if we can't arrange something sooner though

**Comment by Tosin-Balogun** [comment]
@sarawilcox - If we are to do it sooner, it would either be this week (Mon-Fri) or next week (Mon-Tues). After those, I'd be on a month long leave till 10th May 2021.

I second what Henry says about doing sooner because the memory is still fresh, but doing it later should be fine as well 🏃🏿

**Comment by sarawilcox** [comment]
We could perhaps arrange a session with the content community next week but you wouldn't get as broad a range of content people attending as you would at the next content huddle on 29 April. As you say, it's good to do something while it's fresh and Tosin will be on leave soon. Not sure what's the best thing to do. Does @davidhunter08 have a view?

**Comment by sarawilcox** [comment]
Hi @davidhunter08, the next content huddle is 29 April, 2pm. Would this work for you? I told Tosin that I'd look at the presentation slides before we present them to the content community but haven't had a chance yet. I think they may need a bit of intro. Can I look at them nearer the time?

**Comment by sarawilcox** [comment]
Decided not to share with content team for now. We'll share the findings from the contribution research that Indu is kicking off.
