### ISSUE TITLE
Publish community contribution video to public channels

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#1098]
## What
We need to publish the recorded video of the community presentation done with our internal professionals

## Why
We need to reach out to our external community who are unable to attend our internal professional meet ups. This should let them get visibility of our plans and perhaps encourage them to get involved more

## Task list
- [ ] Seek out NHS YouTube managers
- [ ] Publish video on YouTube channel
- [ ] Share video on public channels

**Comment by lucyha** [comment]
Meeting needs to be set-up with the NHS digital comms team

**Comment by sarawilcox** [comment]
We decided to store the video on Confluence but not publish it on YouTube.
