### ISSUE TITLE
Use Adobe Analytics instead of Google analytics on the service manual

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-service-manual#1101]
## Description

We currently use Google analytics on the NHS digital service manual, however we use Adobe Analytics on the NHS website. Using AA would give us more features, reporting and support from the analytics team within NHS.UK.

We tried to use AA in the past but the click events interfered with the "Copy code" functionality on the component examples.

## Tasks

- [x] Remove Google analytics
- [x] Implement Adobe analytics 
- [ ] Setup reporting dashboards with the analytics team
- [x] Test the "Copy code" functionality with AA
