### ISSUE TITLE
Setup reporting dashboards with the analytics team

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1122]
## What

We are now using Adobe Analytics, which provides more features, reporting and support from the analytics team within NHS.UK.

## Tasks

- [ ] Review current analytics reports
- [ ] Agree what analytics are required by team
- [ ] Speak to Julius for advice
- [ ] Provide requirements to Julius to create dashboard

**Comment by georginaplatt** [comment]
Showed Julius the analytics captured via google analytics over the past few quarters & asked advice on what analytics he can provide in a dashboard & what he needs.
Needs to know:-
- user needs
- key journeys
- problem statements
- priorities list of pages to focus 

We talked about analytics request from comms & capturing these analytics: -

- Website visitors
- Unique page views
- Referrals to website 
- Direct referrals
- Social media referrals
& - bounce rates
& - linking to GitHub
& - serverside analytics - azure & splunk (captures more granular data which cookies block)

Direct referrals = signposting or exit to..

**Comment by sarawilcox** [comment]
Is it possible to add downloads of:
- the design principles posters, from this page: https://service-manual.nhs.uk/design-system/design-principles
- the accessibility posters, from this page: https://service-manual.nhs.uk/accessibility?

@georginaplatt Is "linking to GitHub" click throughs to GitHub?

**Comment by georginaplatt** [comment]
Yes we can chat tomorrow about the priorities list &
 click throughs to github @sarawilcox

**Comment by chrimesdev** [comment]
@georginaplatt is this done now? can we close this issue?
