### ISSUE TITLE
EPIC: Wagtail frontend plugin review

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1159]
## To do

- [x] Review open issues and pull requests and decide what to do with them
- [ ] Review the Wagtail frontend plugin to identify any inconsistencies with the NHS.UK frontend (such as missing components like Tag). 
- [ ] Come up with a plan for new features and improvements
- [ ] Clarify the process for path to live for updating the NHS website
- [ ] Hold some kind of review with the content profession to see what they need or think is missing
