### ISSUE TITLE
EPIC: Remove Nav A-Z and List panel components from frontend

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1186]
## What

We need to remove nav A-Z and list panel components from NHS.UK frontend and instead use existing components and (possibly new) styles and utility classes.

## Why

So we will reduce the duplication of code – making the frontend easier to maintain and increase its performance.

## Related to

https://github.com/nhsuk/nhsuk-service-manual/issues/1157

## Done when

We have:

- [x] [created a proof of concept](https://github.com/nhsuk/nhsuk-service-manual/issues/1193)
- [ ] tested the code in a live service
- [ ] made notes on upgrade path
- [x] removed the code from the frontend (with changelog notes)
- [x] communicated the changes to our users

**Comment by georginaplatt** [comment]
I remember Adam saying he was waiting on #880 so they both could be released at the same time. I know this EPIC #1186 & last FE ticket is in review [#740](https://github.com/nhsuk/nhsuk-frontend/pull/740) is a breaking change. 

Is there much work to do on this one @DomBaker as #880 is due to be released Monday can this be released together? @sarawilcox @henocookie

**Comment by henocookie** [comment]
@DomBaker or @truecroft2 do you know if the changes have been tested on another live service? I know we had an issue with an old Nav A-Z implementation on the [A to Z of NHS health writing page](https://service-manual.nhs.uk/content/a-to-z-of-nhs-health-writing) in the Content style guide. Interested to know if other services that have upgraded to use the latest nhsuk-frotnend have similar issues.

**Comment by DomBaker** [comment]
Hi Henry, as long as other services are using the new Nav A-Z code and have updated to the latest version of the frontend library they shouldn't have any issues, now that it is no longer a component and just straight HTML it shouldn't display differently on other services unless they have conflicting custom CSS in their project
