### ISSUE TITLE
EPIC: Redesign Hero banner component and add guidance to the service manual

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1187]
## What 

We need to redesign the Hero banner component and add guidance for it to the service manual. 

## Why 

So that the hero component meets our users needs and has clear guidance on its context of use.

## Related to

https://github.com/nhsuk/nhsuk-service-manual/issues/1157

## Done when

We have:

### Discovery

- [x] collated examples of the hero banner being used (in NHS services)
- [x] [collated examples of a hero banner being used (in other services)](https://github.com/nhsuk/nhsuk-service-manual/issues/1188)
- [x] reviewed hero banner usage
- [ ] researched the use of images

### Research

- [ ] spoken to the community and understood their user needs and research on the hero banner

### Design

- [ ] created mock-ups (including the different variants)
- [ ] prototyped and tested solutions

### Development

TBD

### Guidance

- [ ] drafted guidance
- [ ] reviewed guidance
- [ ] design system working group review?

### Comms

TBD

**Comment by nancyhalladay24** [comment]
I have compiled a slide deck with [all discovery research so far here](https://hscic365.sharepoint.com/:p:/s/InternalServiceManual/EdOMgnd_ly5FsnltvupRID0BUdYWE96bGF5AWSE0YAHhkg?e=VGeaq6)

**Comment by nancyhalladay24** [comment]
After a meeting with Dean and Ben we decided that since the component was designed predominantly as branding for NHS.UK and not specifically with UCD principles in mind. It’s best if we don’t produce guidance and promote others to use it.
We think it would be more beneficial to produce homepage guidance, as the hero banner is a component of a homepage.

Therefore, the work we have identified to be done going forward:
- The homepage guidance is more in IA’s remit and so Ben has spoke to them to add it to the backlog. This still needs to be prioritised, so may take a while before work begins.
- There needs to be some additional work around branding on a homepage. Would be good to organise some chats to better understand this, it might be more media/social teams remit to write guidance on this. Good to chat with Eva Lake.
- Comms about removing the hero banner from the front end library will need to be written and released. This may be a good opportunity for a blog post as well.
- Comms and homepage guidance will need to be released at the same time so that people have a chance to amend their design in preperation for the component to be removed from the front end.
