### ISSUE TITLE
Review draft guidance on subtitles and colour and iterate

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1308]
Rich Kelly has drafted some guidance. 

### Tasks
- [x] Review and consider including it in the accessibility guidance:
https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/347#issuecomment-878137153
- [x] Sara to make content changes
- [x] Run it by Leigh and Alistair
- [ ] Publish

**Comment by karlgoldstraw** [comment]
This guidance as it stands looks great as a starting point. 
I think there's more guidance we can add in due course but we can add this later.

**Comment by sarawilcox** [comment]
I've reopened this Karl as I need to do the content review. I'll take your name off though.

**Comment by sarawilcox** [comment]
With Leigh, Alistair and @mcheung-nhs for review.

**Comment by sarawilcox** [comment]
Approved by Leigh and Michael.
@danjohnstonUX, would you mind casting your eye over this on review/1-subtitles please? Just to make sure all looks OK from a design point of view. If you're happy with it, it's ready to release.

**Comment by sarawilcox** [comment]
Ready for release.
