### ISSUE TITLE
EPIC: Onboarding

### ISSUE THREAD

**Issue by EllenDoyle** [nhsuk/nhsuk-service-manual#1311]
## What; 
New starters on SM Team. Need to create a consistent onboarding plan.
## Why;
All new starters need consistent induction to the team and workload.
## Done when;

- [x] Start date agreed
- [x] Line manager agreed
- [x] HR forms completed as necessary
- [x] Team discussion about where new starter first in the team and work they should do
- [x] Invite to relevant meetings and ceremonies
- [x] Ensure they have access to relevant channels such as Slack, GitHub, SM public channel, etc
- [x] For externals ensure new starter has VM, email address, etc on request (speak to PMO) (not relevant for Dan, Catherine and Tom)
- [x] Invite to Design System Day, Style Content meeting, S&T, etc
- [x] [Develop and share a history of the Service Manual Team](https://github.com/nhsuk/nhsuk-service-manual/issues/1312)
- [x] Get portfolio code from PMO and assign to new starter
- [x] Get on NHS.UK distribution list (PMO)

**Comment by EllenDoyle** [comment]
To raise the written offer for a new permie HR need the following:

To be line manager:
Internal or external candidate: Internal
Are they currently a temp or contractor with NHS Digital: No
Starting salary (as they’re internal this is either bottom of the band or in line with their current paypoint if acting up / sideways move):
Which office they’ll be based in:
Whether they have verbally accepted and are aware references (current line manager) will be contacted:
HR then process the details and the onboarding team will send out the written offer and start the onboarding process. They will then:

•	send out a conditional offer
•	check internal ‘references’ with the current line manager
•	send the unconditional offer
•	ask the ‘to be’ line manager to confirm a start date
•	raise the NOV
•	raise the candidate contract
•	update ESR

**Comment by EllenDoyle** [comment]
https://trello.com/b/fm5SAxAp/dm-2021-onboarding-template-updated-june
Work already been taken in NHS.UK

**Comment by georginaplatt** [comment]
Added Tom to service-manual team on GitHub.
Raised adding Catherine & Dan on NHS.UK organization on GitHub - Keith will add on Mon.
Then can add both to service-manual team Mon.

**Comment by EllenDoyle** [comment]
Confluence Access:
Morning! This is the process for getting access to confluence but if you have any difficulty either raise it in this channel #jira-confluence-admin or Matt Higgins helped me last time setting up your access :slightly_smiling_face:
https://nhsuk.slack.com/archives/CM6L7RR2T/p1614873992002200
Andrew Siddall
Copying access info from #jira_confluence_2020_migratio
To request access to Jira and Confluence you need to;
1. Fill out the Central Development Toolset Form on - https://estore.hscic.gov.uk/
2. Email ssd.nationalservicedesk@nhs.net and request your new user to be added to the following groups;
For Jira:
nhsukjira_users
jira-users
+ nhsapp_users - for NHS App
+ nhs_111_online - for 111 Online users
+ nhsuk_users - for NHS.UK
For Confluence:
nhsukconfluence_users
+ nhsapp_confluence_users - For NHS App users
+ 111online_confluence_users - for 111 Online users
+ nhsuk_users - for NHS.UK (edited)

**Comment by EllenDoyle** [comment]
Tom starts with us 26th June but is away until 29th June - LM stays as present
Catherine 26th June - Georgina to LM
Dan 2nd August - Ben Cullimore to LM

All added to Confluence and annual leave pages 28/7/21
