### ISSUE TITLE
EPIC: Prototype kit known improvements

### ISSUE THREAD

**Issue by karlgoldstraw** [nhsuk/nhsuk-service-manual#1422]
## What 

There is a need to continual develop the prototype kit to ensure it is in line with the latest development practices. This EPIC is to allow some concentrated effort to review improvements for the prototype kit.

## Originates from 

nhsuk/nhsuk-service-manual#1062 

## Why

Without continuous development the prototype will lose its value as a critical resource for designers and developers.

## Must
- [ ] nhsuk/nhsuk-service-manual#1391 
- [x] nhsuk/nhsuk-service-manual#1399 
- [ ]  nhsuk/nhsuk-service-manual#1425 
- [ ] nhsuk/nhsuk-service-manual#1396 
- [ ] nhsuk/nhsuk-prototype-kit#392 
- [ ] nhsuk/nhsuk-service-manual#1417 
- [ ] nhsuk/nhsuk-service-manual#1418 

## Could
- [ ] nhsuk/nhsuk-service-manual#1397 
- [ ] nhsuk/nhsuk-service-manual#1398 
- [ ] nhsuk/nhsuk-service-manual#1401 
- [ ] nhsuk/nhsuk-service-manual#1419 
- [ ] nhsuk/nhsuk-service-manual#1420 
- [ ] nhsuk/nhsuk-service-manual#1421

**Comment by karlgoldstraw** [comment]
In an NHS design huddle, @GrilloPress asked a bunch of people some questions about prototyping, and the prototype kit. https://app.mural.co/t/nhsdigital8118/m/nhsdigital8118/1625739641256/3ebd113110bdae75709c07fcc5b0412581c32061?sender=karlgoldstraw0227

**Comment by Tosin-Balogun** [comment]
# What
On 3rd of August, two interaction designers asked for help with the prototype kit. Due to an adjacent work for the NHSUK design repo, I decided it was good to documented some of the comments they made while trying to use the kit

# Who
- P1: A novice designer who switched from visual design into interaction design working for NHS England on the [Learning Hub](https://learninghub.nhs.uk/)
- P2: An interaction designer working on digital transformation of screening

# Feedback
P1: “Do you guys have a video tutorial I can follow”
Because they could not use the guidance on the kit properly

P2: “You cannot find where everything is, and you get frustrated and give up”
“If all you want to is use a template and add components, its fine but when you want to do anything different”
“There was nunjucks at the top, I didnt know what to do”
“I understand normal css, but I don’t know where to do it here”
“I cannot just add a navigation bar to the template. It just wasn’t having it”
“Mentally, I just gave up”
“I dont want to make frankenstein code, because I want to do it proper for the devs”
