### ISSUE TITLE
EPIC: Improve Service manual IA

### ISSUE THREAD

**Issue by CatherineReader** [nhsuk/nhsuk-service-manual#1516]
## What

Improve the information architecture of the Service Manual to better suit current user needs.

## Why

So that users can find information that is relevant to them with ease. We are publishing IA guidance on the service manual and want to ensure our IA follows the guidance we are publishing. 

## Tasks
- [ ] Make small changes to the Service manual IA to accommodate IA guidance at first #1524 
- [ ] Review how well the service manual IA meets the current user needs of people using the service manual #1526 
- [ ] Following review, ideate changes to the Service manual IA that would address findings
- [ ] Usability test the proposed ideas with users
- [ ] Analyse usability testing results and decide on an approach to take forward
- [ ] Work with developers in the team to implement agreed changes
