### ISSUE TITLE
Plan the next Design System Working Group (DSWG) session

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#1522]
## What

Plan the next Design System Working Group (DSWG) following the first DSWG session which was recently restarted.

## Why

So that the DSWG continues and the next session is organised in advance with invites sent to the right people.

## Tasks
- [x] Agree who will organise and run the next DSWG session (likely @henocookie or @danjohnstonUX)
- [x] Send out an invite for the next DSWG session to members who attended the first as well as those who showed an interest on Slack following @henocookie's message about the DSWG
- [x] Organise any materials and tools required to host the next DSWG session
- [x] Arrange 10 minutes (maximum) to share the outputs from the October DSWG session at the next session
- [x] Ensure that outputs and decisions from the last DSWG season (#1502) have been shared with those who attended the firsts DSWG session and the wider digital health and care sector
