### ISSUE TITLE
Small change to the service manaul's IA to accommodate the first tranche of IA guidance

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#1524]
## What

Make small changes to the service manual's information architecture (IA), reviewed and published to the service manual website which accommodates the first tranche of IA guidance.

## Why

So that:
- there is a place in the service manual for the first tranche of IA guidance
- we can plan to test with users and analyse analytics to see how useful and understood the first tranche of IA guidance is

## Tasks
- [x] Prototype small changes to the service manual's IA to accommodate the latest iteration of the first tranche of IA guidance
- [x] Make any follow up changes needed
- [x] Final review of service manual changes with the wider service manual team
