### ISSUE TITLE
Test and monitor first tranche of IA guidance

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#1561]
## What

After publishing the first tranche of IA guidance to the service manual website, we should plan to test how useful and usable it is for people.

## Why

So that:
- we can test with users and analyse analytics to see how useful and understood the first tranche of IA guidance is
- we know what changes may be needed to improve the first tranche of IA guidance
- we have a clear understanding if there is an appetite for more IA guidance for service manual users

## Tasks
- [ ] Plan what research questions and methods we want to use to see how useful and usable the guidance is (with @amyj2110 @MuawiyahM as well as Lisa and Matt from the IA team
- [ ] Set up a plan to monitor link clicks and visits to the IA guidance pages
- [ ] Report to the wider service manual team the findings
