### ISSUE TITLE
1-to-1s with service manual team to explore the understanding of current contribution processes

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#1607]
## What
Explore team’s understanding of current contribution processes using 1-to-1 interviews. 

## Why
So we can understand the team’s needs and pain points around existing contribution processes.

## Epic this is a child of
EPIC: Fixing the design system contribution process #1623  

## Tasks
- [x] Create a discussion guide with @amyj2110's help
- [x] Book 1-to-1 time with each member of the service manual team
- [x] Collate and analyse notes from the 1-to-1s

**Comment by henocookie** [comment]
Discussion guide WIP: https://hscic365.sharepoint.com/:w:/s/InternalServiceManual/EaTH-AEyYdBPssv2WtY6YtABMONWoKzws2LBc4SI3mpqPg?e=VNxKbK

**Comment by henocookie** [comment]
1-to-1s with the team completed and most analysis done. Myself and @ambchang are sharing the findings and next step recommendations with the whole team at today's sprint retro and review session
