### ISSUE TITLE
Create presentation to share with NHSx about the NHS digital service manual, related to service assessments

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#1634]
## What

Create a presentation that details the NHS digital service manual and its history for an audience of design assessors from NHSx to share how the service manual can help with service assessments.

## Why

So design assessors can utilise guidance, standards and principles that already exist in the NHS digital service manual to do service assessments against.

## Tasks
- [x] Consolidate the slides Karl shared in his handover
- [ ] Add detail about the GOV.UK and NHS service standard, which both say that teams need to use the GOV.UK or NHS design systems (this is what design assessors will be assessing people against)
- [ ] Add detail around the fact that the GOV.UK and NHS design systems have a lot in common but some differences too
- [x] Add detail around the ways that teams can engage with the service manual, in particular the service manual public Slack workspace, where they can also get input from other NHS teams

**Comment by henocookie** [comment]
Started a presentation that originated with some slides Karl worked on, covering the design system. I have expanded the deck to cover a wider (but still high-level) overview of the NHS digital service manual: https://docs.google.com/presentation/d/1ZG33iwcIHQrdwy9pKK8uU6XbqSmsE_nYFdFOrC3Yw7o/edit?usp=sharing

**Comment by henocookie** [comment]
A lot of the detail which could be suitable to add to this deck could be found in the "vision and strategy for the NHS digital service manual​" deck @georginaplatt is working on
