### ISSUE TITLE
Additional languages research due diligence

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#1638]
## What
Now that the additional languages discovery is over, we need to make sure all the user research documentation is up to date.

## Why
Doing our due diligence and making sure everything is there for future generations of the service manual team / people who work on additional languages.

## Tasks
- [x] Ensure all recordings are uploaded to service manual sharepoint
- [x] Ensure all notes are on the Mural board
- [x] Delete any files not needed
- [x] Ensure documentation is uploaded to service manual Confluence pages
