### ISSUE TITLE
Set up next steps following team community contribution research

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#1648]
## What
Following the playback of research into the team’s understanding of current contribution processes, we need to plan and set up next steps to progress the work to improve contribution processes.

We could do this by using "how might we?" statements or another method to be decided.

## Why
So we can progress the community and contribution work to ensure findings and needs are assessed by changes the team agree to follow.

## Epic this is a child of
EPIC: Fixing the design system contribution process #1623  

## Tasks
- [ ] Arrange a time for @henocookie and @PeteKowalczykNHS to discuss the findings, next step recommendations & feedback from the team
- [ ] Plan an ideation method to use
- [ ] Run the ideation (as a team and/or individuals depending on the method decided on)

**Comment by henocookie** [comment]
@PeteKowalczykNHS as this issue is for setting the next steps, it might be good if we set up new issues for some of the individual parts of the next steps. Easier to track and all that!

**Comment by henocookie** [comment]
# Next steps

## Backlog refinement
- [ ] Henry and possibly Sara host a knowledge sharing session on the GitHub repositories and community backlog projects
- [ ] At the end of that session, Pete to share a set of instructions with the team to go through each of the 3 backlog projects and add comments to update issues as well as move issues to the relevant column. For example, move out of "in progress" and into "proposed" if we're not actively working on it
- [ ] Mini retro on how that whole exercise went on Thursday 16th (as part of ceremonies day) - run by Henry and Pete. Do a quantitative comparison of the number of issues in the backlog (before and after)
- [ ] (stretch task) look at the issues view, sorted by "least activity" as a team and go through the low activity tickets to see which we can close

Then around mid-January
- [ ] Support @georginaplatt and @EllenDoyle in running follow-up refinement sessions with the team
- [ ] Plan to these refinement sessions quite regularly, organised primarily by product/delivery roles but involving the whole service manual team in the session 

## Role and responsibilities

- [ ] Run a session week commencing 13th December to review the job stories for a contribution, and acceptance criteria (tasks) for each job story - Run by Henry and Pete. Edit these, add stuff, remove stuff in the session. Move the job stories around on a Mural board, as a team moving them under the profession that should be doing them
- [ ] Ask the whole team to add comments on the acceptance criteria (tasks) for each job story once moved under the professions that should be doing them
- [ ] Allow the team to work using these responsibilities as a reference and **review how it is going at a retro in the new year** and iterate where needed

## Triaging new requests (community support rota)

- [ ] Create a plan to show what rota we propose - present this in the new year - Henry to make the deck and present
- [ ] Henry to check what the GOV process is for running their prototype kit support rota
- [ ] Adjust proposal based on team feedback and start running the rota!
- [ ] Review how the rota is going once a month (every 2 sprints) and iterate where needed

**Comment by henocookie** [comment]
[Service manual repositories and community backlog mini-retro.pdf](https://github.com/nhsuk/nhsuk-service-manual/files/7727318/Service.manual.repositories.and.community.backlog.mini-retro.pdf)

**Comment by sarawilcox** [comment]
Pete sent me links to some slides before he left. @henocookie, will you be taking this piece of work forward?

**Comment by henocookie** [comment]
Leaving this issue open but removing from the [service manual team sprint board project](https://github.com/orgs/nhsuk/projects/2) as the team is now operating at a very reduced capacity
