### ISSUE TITLE
Follow up after December 2021 DSWG session

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#1649]
## What

Follow up and share the outcomes following the December 2021 DSWG session (#1522).

## Why

So that the outcomes from the session are documented and actions can be made after agreeing on the next steps to take with key contributors.

## Epic this is a child of
EPIC: Design System Working Group (DSWG) #952 

## Tasks

- [x] Create a presentation summarising the agenda, voting and discussion following the session
- [x] Arrange 30 minutes to share the outputs from the session with the service manual team and agree on urgent and longer-term steps to take
- [x] Arrange 20 minutes to share the outputs from the session and agree on the next steps to take with key contributors
- [x] Arrange 10 minutes to share the outputs from this session at the next DSWG session
- [x] Ensure that outputs from the session have been shared with those who attended the session and on GitHub for the wider health and care sector

**Comment by henocookie** [comment]
All tasks to initially follow up from the December DSWG session have been completed.

**Comment by henocookie** [comment]
Link to the outcomes slide deck: https://docs.google.com/presentation/d/1ZtowLEj10x77st5aOREuAjwevuFTXjmwmzzYaESruIA/edit?usp=sharing
