### ISSUE TITLE
Prep for Jan Style Council meeting 

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1663]
## What

Invite people, prepare the agenda and slides for the meeting.

## To do

- [ ]  Arrange room - not needed
- [ ]  Agree meeting date
- [ ]  Arrange Teams meeting and send out invite with notes from last meeting
- [ ]  Firm up agenda 
- [ ]  Get issues ready with colleagues
- [ ]  Make sure that GitHub is up to date
- [ ]  Share agenda and info about topics up for discussion - by email, on NHS.UK and NHS digital service manual Slack
- [ ]  Prepare slides 
- [ ]  Sent out slides the day before

Things to consider
- [ ] Review guidance on links and prepare proposals
- [ ] [Left align content](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/297)
- [ ] Come back to image captions.

Other possible topics:
Possibly:
- Guidance on choosing the right format for content
- Image guidance
- [ ] [Links](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/324)
- [ ] booster - Jason? 
- [ ] left alignment - Sam Saw
- [ ] perhaps also some terms from Pete
- [ ] Do and don't list feedback

Not yet ready:
- [ ] Deaf people and deafness/ versus hearing loss - https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/211#issuecomment-845010321
- [ ] autism - "autistic people" - 
- [ ] [contractions](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/266) - see comment from Karin 
- [ ] social media guidance - probably won't be ready yet - Joe
- [ ] [long image descriptions](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/309)

**Comment by sarawilcox** [comment]
Close issue. Done.
