### ISSUE TITLE
Plan the January 2022 DSWG session

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#1671]
## What

Plan the January 2022 Design System Working Group (DSWG) session.

## Why

So that the DSWG continues and the next session is organised in advance with invites sent to the right people.

## Epic this is a child of

EPIC: Design System Working Group (DSWG) #952 

## Tasks
- [ ] Agree who will organise and run the next DSWG session (either @henocookie or @danjohnstonUX)
- [ ] Find contributions in the community backlog which are ready to take to DSWG
- [ ] Organise any materials and tools required to host the next DSWG session
- [ ] Send out an invite for the next DSWG session to members in advance
- [ ] Arrange 10 minutes (maximum) to share the outputs from the December 2021 DSWG session at the next session
- [ ] Ensure that outputs and decisions from the last DSWG season (#1649) have been shared with those who attended the previous DSWG session and the wider digital health and care sector

**Comment by henocookie** [comment]
DSWG is now being paused due to a heavily reduced team. Communication to DSWG members will be sent to explain this.

**Comment by henocookie** [comment]
Communications sent by email to current DSWG members and the [Wiki page](https://github.com/nhsuk/nhsuk-service-manual/wiki/Design-System-Working-Group-(DSWG)) has been updated informing members of the current DSWG pause.
