### ISSUE TITLE
Update /service-manual-team with team members

### ISSUE THREAD

**Issue by theonlymojo** [nhsuk/nhsuk-service-manual#1720]
### **What**
Update /service-manual-team with current active team members. This page should be a list with the following names:
Georgina Platt - Product Manager
Mohammed Meah - Delivery Manager
Sara Wilcox - Content Designer
Henry Cookson - Interaction Designer

### **Why**
So the information is up to date for those interested and to avoid people not on the team inadvertently being contacted

### **Related to**
https://service-manual.nhs.uk/service-manual-team

### **Tasks**

- [x] @georginaplatt to confirm ticket details
- [x] @henocookie to update for review
- [ ] Schedule release/update
- [ ] Deploy!

**Comment by henocookie** [comment]
Work in progress on the [update-team-page branch](https://github.com/nhsuk/nhsuk-service-manual/tree/update-team-page)

**Comment by henocookie** [comment]
Included in the [v5.7.1 release](https://github.com/nhsuk/nhsuk-service-manual/releases/tag/v5.7.1)
