### ISSUE TITLE
Follow up after April 22 Style Council and publish updates

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1761]
### What
Write up of meeting notes and actions taken and share with attendees
Content changes published in service manual

### Done when

-  [x] notes written up
-  [x] action points agreed and allocated
-  [x] notes and actions shared on Slack content channel 
-  [x] notes and actions approved by clinicians 
- [x] agree when to publish new standard
- [x] GitHub updated
- [x] Outcomes of Style Council meeting communicated
- [x] Make other minor changes before publishing
- [x] Amendments made to style guide and published

### Other actions
- [ ] respond Amy at GDS re COVID style guide

### Related task

**Comment by sarawilcox** [comment]
- [ ] Content creation principles #1740
- [ ] [Reading age](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/258) - PIF feedback
- [ ] [Negative](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/230) - we already have positive
- [ ] [Specialty of speciality](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/418)
- [ ] Report on skin symptoms update
- [ ] [Report on user research - content style guide and inclusive content guide](https://github.com/nhsuk/nhsuk-service-manual/issues/1728)

**Comment by sarawilcox** [comment]
For future consideration:

### May?
- [ ] 1 versus one for professional audiences: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/321#issuecomment-1031635148
- [ ] Skin symptoms - [add further examples](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/181#issuecomment-1051006057)
- [ ] [Skin symptoms - Pathways user research](https://github.com/nhsuk/nhsuk-service-manual/issues/1653)
- [ ] [Links](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/324) - update on analytics
- [ ] [Choosing content formats - draft in NHS.UK Confluence](https://nhsd-confluence.digital.nhs.uk/display/SMDS/Choosing+content+formats) - see GitHub issue #1672 1680

## Not yet ready:
- [ ] Deaf people and deafness/ versus hearing loss - https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/211#issuecomment-845010321
- [ ] Do and don't list feedback
- [ ] autism - "autistic people" - 
- [ ] [contractions](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/266) - see comment from Karin

**Comment by sarawilcox** [comment]
Amendments to style guide:
- added entry for negative to A to Z
- amended entry for positive in A to Z
