### ISSUE TITLE
Plan October 2022 Style Council

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1772]
## What

Invite people, prepare the agenda and slides for the meeting.

## To do

- [x]  Arrange room - not needed
- [x]  Agree meeting date
- [x]  Arrange Teams meeting and send out invite with notes from last meeting
- [x]  Firm up agenda 
- [x] Prep slides 
- [x]  Get issues ready with colleagues
- [x]  Make sure that GitHub is up to date
- [x]  Share agenda and info about topics up for discussion - by email, on NHS.UK and NHS digital service manual Slack
- [x]  Prepare slides 
- [x]  Sent out slides the day before

### Report back on April meeting
- [x] [Negative](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/230) - rethink the example
- [x] [Specialty of speciality](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/418)
- [x] Opticians etc

### September

- [x] [voting rights](https://github.com/nhsuk/nhsuk-service-manual/issues/1773)
- [x] Review example of negative
- [x] SMS (text message): https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/366
- [x] triage: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/427
- [x] clinician: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/446
- [x] online consultation: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/426
- [x] GP appointments - for discussion only: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/424
- [x] COVID entries - coming from GOV.UK: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/275
- [x] ICBs - retrospective
- [x] must, should

## Not yet ready/needs more work
- [ ] learning difficulties/learning disabilities: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/312
- [ ] - [ ] easy read, Braille, large print
- [ ] dentists versus dental practices
- [ ] skip links - wording
- [ ] updates versus reviews
- [ ] 1 versus one for professional audiences: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/321#issuecomment-1031635148
- [ ] Skin symptoms - [add further examples](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/181#issuecomment-1051006057)
- [ ] [Skin symptoms - Pathways user research](https://github.com/nhsuk/nhsuk-service-manual/issues/1653)
- [ ]  [Links](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/324) - update on analytics
- [ ] [Choosing content formats - draft in NHS.UK Confluence](https://nhsd-confluence.digital.nhs.uk/display/SMDS/Choosing+content+formats) - see GitHub issue #1672 1680
- [ ] Deaf people and deafness/ versus hearing loss - https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/211#issuecomment-845010321
- [ ] Do and don't list feedback
- [ ] autism - "autistic people" - 
- [ ] [contractions](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/266) - see comment from Karin 
- [ ] [Reading age](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/258) - PIF feedback

**Comment by sarawilcox** [comment]
Need to write up meeting notes and get clinical sign off.
