### ISSUE TITLE
Plan May or June 23 Style Council

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1883]
## What

Invite people, prepare the agenda and slides for the meeting.

## To do

- [ ]  Agree meeting date - agree with Dom/Emmy, Susie, Graham
- [ ]  Arrange Teams meeting and send out invite with notes from last meeting
- [ ]  Firm up agenda 
- [ ] Prep slides 
- [ ]  Get issues ready with colleagues
- [ ]  Make sure that GitHub is up to date
- [ ]  Share agenda and info about topics up for discussion - by email, on NHS.UK and NHS digital service manual Slack
- [ ]  Prepare slides 
- [ ]  Sent out slides the day before

### Report back on October 2022 meeting
- "clinician"​
- "perinatal"​
- "secure message"​
- "SMS"​
- "triage"​
- a number of coronavirus (COVID-19) related entries

### Mention
- removal of 077718 300 300 phone number

### For June meeting
- [ ] messaging via the App - change to SMS: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/366
- [ ] online consultation: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/426 - pick up with Graham
- [ ] GP appointments - for discussion only: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/424 - see guidance for primary care communications 
- [ ]  Get rid of NHSX and [NHS Test and Trace](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/460), plus [NHSE not NHSEI](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/460)
- [ ] [ Italics](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/463)
- [ ] Examples of how to avoid using [dashes](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/206) - Albert
- [ ] [COVID-19](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/275)
- [ ] Numbers, measurements, date and time - changes re dyscalculia - see [Word doc - NHS England staff only](https://hscic365-my.sharepoint.com/:w:/r/personal/sawi10_hscic_gov_uk/Documents/Standards%20and%20service%20manual/Style%20guide%20page%20on%20numbers,%20measurements,%20dates%20and%20time.docx?d=wd76abe022a7a4a9da2c3e5aed6dc2e3a&csf=1&web=1&e=VghHLR) - Graham
- [ ] [Febrile convulsions](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/158)? Cedrik
- [ ] [Time format in patient information](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/167) - use of colon - see message on Slack #content channel

## Not yet ready/needs more work - possibly next meeting
- [ ] add entry for 111 (phone no), e.g. call 111 - see NHS 111 online?
- [ ] number one (Albert) (https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/162)
- [ ] contractions (Albert) (https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/322)
- [ ] [email and phone links](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/363)
- [ ] learning difficulties/learning disabilities: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/312
- [ ] - [ ] easy read, Braille, large print
- [ ] dentists versus dental practices
- [ ] skip links - wording
- [ ] updates versus reviews
- [ ] 1 versus one for professional audiences: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/321#issuecomment-1031635148
- [ ] Skin symptoms - [add further examples](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/181#issuecomment-1051006057)
- [ ] [Skin symptoms - Pathways user research](https://github.com/nhsuk/nhsuk-service-manual/issues/1653)
- [ ]  [Links](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/324) - update on analytics
- [ ] [Choosing content formats - draft in NHS.UK Confluence](https://nhsd-confluence.digital.nhs.uk/display/SMDS/Choosing+content+formats) - see GitHub issue #1672 1680
- [ ] Deaf people and deafness/ versus hearing loss - https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/211#issuecomment-845010321
- [ ] Do and don't list feedback
- [ ] autism - "autistic people" - 
- [ ] [contractions](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/266) - see comment from Karin 
- [ ] [Reading age](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/258) - PIF feedback
