### ISSUE TITLE
Prep task list for release, with service manual guidance

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#2030]
We have a PR for the frontend: https://github.com/nhsuk/nhsuk-frontend/pull/969. This will need finalising for release.

Then we need a page in the design system to support it. 

Backlog issue: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/304

GOV.UK design system: https://design-system.service.gov.uk/components/task-list/

## To do

- [x] Review component and pattern guidance in service manual (https://github.com/nhsuk/nhsuk-service-manual/pull/2031)
- [x] Content 2i for guidance
- [x] Remove commented out code
- [x] Remove temp fix to let us see examples
- [x] Finalise frontend code / PR (https://github.com/nhsuk/nhsuk-frontend/pull/969)
- [x] Design review
- [x] Frontend testing

**Comment by sarawilcox** [comment]
Released today:

- [task list component](https://service-manual.nhs.uk/design-system/components/task-list)
- [complete multiple tasks pattern](https://service-manual.nhs.uk/design-system/patterns/complete-multiple-tasks)
