### ISSUE TITLE
EPIC: Accessibility guidance (update + assess existing guidance against WCAG 2.2)

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#669]
## What
- Research the usage and impact of accessibility guidance and update existing guidance to reflect the feedback from Nomensa.

- Take into account recent work on a tool to help NHS.UK comply with WCAG 2.1.

- **Bring the guidance up to date with WCAG 2.2 (expected publication early 2023) - with a deadline for compliance likely 6 to 12 months after publication.**

- consider how we can integrate the checklists at: https://nhsdigital.github.io/accessibility-checklist/

## Why
The guidance was published around a year ago. We need to know how effective it is and update it to take account of recent audit findings. Also to bring it into line with WCAG 2.2, expected to come into force in 2023.

## Related issues
- [**EPIC: WCAG 2.2 accessibility audit/review and update of design system**](https://github.com/nhsuk/nhsuk-service-manual/issues/1832)
- [Clarify what we say about page position in accessibility guidance](https://github.com/nhsuk/nhsuk-service-manual/issues/760)
- [Cross check information in the Content role section of the accessibility guidance with SEO guidance being provided to NHS.UK for conflicts #759](https://github.com/nhsuk/nhsuk-service-manual/issues/759)
- [Updates to accessibility guidance, re legal guidance ](https://github.com/nhsuk/nhsuk-service-manual/issues/1816)

## Must

- [x] [Review the accessibility pages](https://github.com/nhsuk/service-manual-internal/issues/60)
- [x] [Record google analytics on accessibility pages on the service manual](https://github.com/nhsuk/nhsuk-service-manual/issues/917)
- [x] [Review accessibility audits](https://github.com/nhsuk/nhsuk-service-manual/issues/917)
- [x] [Work with the accessibility working group and accessibility lead to identify areas for improvement](https://github.com/nhsuk/nhsuk-service-manual/issues/1265)
- [ ] [Set up a meeting with Leigh/Michael to progress Accessibility Guidance](https://github.com/nhsuk/nhsuk-service-manual/issues/669)
- [x] Create a slide deck of recommended changes
- [x] **NEW - Audit, review and recommend changes to the guidance in light of WCAG 2.2**
- [x] Update the accessibility guidance
- [x] Publish the revised accessibility guidance

Also include:
- [ ] [Contact for accessibility questions](https://github.com/nhsuk/nhsuk-service-manual/issues/960)
- [x] [Update compliance date for accessibility](https://github.com/nhsuk/nhsuk-service-manual/issues/959)
- [ ] [Review accessibility guidance on page titles](https://github.com/nhsuk/nhsuk-service-manual/issues/1018)

## Should

- [ ] Publish a blog on the new accessibility guidance

## Outcome

Revised accessibility guidance published as part of the Service Manual

**Comment by sarawilcox** [comment]
GDS video: [What WCAG 2.2 means for UK public sector websites and apps - on YouTube](https://www.youtube.com/watch?v=H6AW6rx91U4)

**Comment by sarawilcox** [comment]
Done. Published: https://service-manual.nhs.uk/accessibility/new-accessibility-requirements-wcag-2-2
