### ISSUE TITLE
EPIC: Open ways of working (planning)

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#672]
## What

The team have been funded to deliver a piece of work around open source / open ways of working / inclusion.

## Why

We will need to start a discovery of this piece to determine the problems we are trying to solve and to establish the goals of the project.

## Must

- [x] [Meeting with Ian Pheonix](https://github.com/nhsuk/service-manual-internal/issues/5)
- [x] [Define scope of the work](https://github.com/nhsuk/service-manual-internal/issues/6)
- [x] [Draft document summarising scope of inclusion work ](https://github.com/nhsuk/service-manual-internal/issues/40)
- [x] [Set up an initial meeting with the NHS.UK inclusion working group](https://github.com/nhsuk/service-manual-internal/issues/38)
