### ISSUE TITLE
EPIC: Guidance on skin symptoms and inclusive language around ethnicity 

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#673]
## What

Publish content guidance around skin symptoms on diverse skin tones and other guidance on inclusive language around ethnicity.

## Why

Ethnicity is a key factor in some health conditions and we often need to refer to ethnicity in content on health information pages. 

In the past, for example, our content has focussed on skin symptoms on white skin but we need to make sure that our content is helpful to people with a diverse range of skin colours.

## Must
- [x] Review the work of the NHS.UK team working on skin symptoms - see [Skin symptoms #181](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/181)
- [x] Review our use of [the word "BAME" and how we talk about different ethnic groups](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/295), for example "Afro-Caribbean". 
- [x] Review our use of [black, white, brown] etc for skin and in relation to ethnicity](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/292)
- [x] [Carry out user research with the community to make sure that our recommendations are appropriate ](https://github.com/nhsuk/nhsuk-service-manual/issues/1183)

Tasks to take forward from user research insights, further iteration of skin symptons guidance: -

- [x] #1459
- [x] #1460
- [x] #1461
- [x] #1462
- [x] #1464
- [x] #1465
- [x] #1466
- [x] #1467
- [x] #1575
- [ ] #1653 
- [x] #1651 
- [x] #1652
- long descriptions
- missing content
- research insights section

## Outcome

- [x] Guidance on skin symptoms and inclusive language around ethnicity.

**Comment by sarawilcox** [comment]
See also: [Inclusive content checklist](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/303)

**Comment by sarawilcox** [comment]
Draft guidance on skin symptoms was agreed at the May Style Council meeting. Subject to clinical approval. 
See [Follow up action/publish changes after May Style Council meeting](https://github.com/nhsuk/nhsuk-service-manual/issues/1069).

**Comment by sarawilcox** [comment]
We've published the guidance, but might want to mop up a few other issues in this epic.

**Comment by CatherineReader** [comment]
Is the final 10% of this done @sarawilcox

**Comment by sarawilcox** [comment]
No, not yet. I need to iterate after user testing. The tasks with the green bullet points above. Probably worth treating them as part of the epic. It's not a huge amount of work.
