### ISSUE TITLE
EPIC: Measuring the value of the service manual

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#676]
## What

Look at how we can measure the value of the service manual.

## Why

NHS Digital need to know how the service manual is performing and the value it is delivering to users.

## Must

- [x] [Research how others have measured the value of service manuals/design systems](https://github.com/nhsuk/nhsuk-service-manual/issues/714)
- [x] [Speak to the GOV.UK Design System team about their approach for measuring the value](https://github.com/nhsuk/nhsuk-service-manual/issues/715)
- [x] [Identify data requirements and sources and collect baseline statistics](https://github.com/nhsuk/nhsuk-service-manual/issues/779)
- [x] Present baseline statistics to team
- [x] [Collect statistics from comms team on social media analytics](https://github.com/nhsuk/nhsuk-service-manual/issues/803)
- [x] [GitHub statistics automations / dashboard](https://github.com/nhsuk/nhsuk-service-manual/issues/805)
- [x] [Create Q3 20/21 analytics report](https://github.com/nhsuk/service-manual-internal/issues/47)

## Outcomes

Document outlining how we can create baseline figures for usage and identify areas to enable ongoing measurement of the value.
