### ISSUE TITLE
EPIC: Cookie guidance

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#678]
## What

The cookie guidance and pattern is presently being worked on by one of the mission teams and when this work is completed it would be useful to share this work with the wider community in the form of guidance and potentially pattern.

## Why

All sites need information on cookie banners and when the NHS UK site has revised it's usage this has been agreed at the highest level within the NHS IG Community and therefore should be used as best practice. This should enabke others to use the agreed wording and styles with minimal IG input as agreed nationally.

## Must

- [ ] Review work undertaken by mission team

- [ ] Develop appropriate guidance to go alongside the patterns proposed

- [ ] Undertaken any necessary user research to gauge the impact of the cookie guidance on end users of services.

- [ ] Implement new guidance within the Service Manual

## Outcome

Cookie Guidance available for use across the NHS domain signed off by senior information governance team within NHS D and available for wider usage outside NHS D.

**Comment by CatherineReader** [comment]
Informed that this was linked to changes GDS were making but they got push back-no one is working on this and there is no issue in the feature backlog.
