### ISSUE TITLE
EPIC: New components - card, tag, responsive table

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#682]
## What

Add guidance to the service for the new and recently updates styles and components in the NHS.UK frontend.

## Why

Not having guidance for the components could result in them being implemented in the contexts they were not designed and tested for.

## To do

Add code to the NHS.UK frontend for the:

- [x] [card component](https://github.com/nhsuk/nhsuk-frontend/issues/639)
- [x] [tag component](https://github.com/nhsuk/nhsuk-frontend/issues/640)
- [x] [responsive table component](https://github.com/nhsuk/nhsuk-frontend/issues/641)
- [x] [updated warning callout component](https://github.com/nhsuk/nhsuk-frontend/pull/630)
- [x] [non visited link style](https://github.com/nhsuk/nhsuk-frontend/issues/643)

Release:
- [x] merge [PR 730](https://github.com/nhsuk/nhsuk-service-manual/pull/730) (component guidance) to master
- [x] [release NHS.UK frontend v4.0.0](https://github.com/nhsuk/nhsuk-frontend/issues/648)
- [x] [update prototype kit](https://github.com/nhsuk/nhsuk-prototype-kit/issues/156)
- [x] [update service manual](https://github.com/nhsuk/nhsuk-service-manual/issues/734)
- [x] [release service manual v3.6.0](https://github.com/nhsuk/nhsuk-service-manual/issues/738)

Comms:
- [x] [Slack announcement](https://github.com/nhsuk/nhsuk-service-manual/issues/776)
- [x] [Twitter](https://github.com/nhsuk/nhsuk-service-manual/issues/777)
