### ISSUE TITLE
EPIC: Service patterns for professional facing systems

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#683]
## What

The NHS digital service manual is presently aimed at patient facing services and there is a different group of users that would benefit from the same type of support, this is systems used by professionals in various settings to support the health of patients. This epic is to investigate how the service manual can provide support to teams developing staff-facing systems.

## Why

Many of the patterns and styles used to improve the services provided to patients may be relevant to teams developing services for professionals.

## Must
- [x] [Set up an initial meeting with individuals working on clinical facing systems](https://github.com/nhsuk/service-manual-internal/issues/37)
- [x] [Review the usage of the service manual by teams developing clinical systems](https://github.com/nhsuk/nhsuk-service-manual/issues/1385)
- [x] [Identify any overlap in patterns, styles etc](https://github.com/nhsuk/nhsuk-service-manual/issues/1386)
- [x] Agree where patterns are relevant to both patient and clinically facing systems and look to make this clear in the manual

## Should

- [ ] Look to include **key** clinical patterns into the service manual as a specific section

## Outcome

Increased use of the service manual across NHS Digital and greater standardisation across healthcare systems.

**Comment by sarawilcox** [comment]
Related issues:
- [Review and discuss the 5 issues awaiting triage](https://github.com/nhsuk/service-manual-internal/issues/62)

**Comment by sarawilcox** [comment]
Another task: once we've identified components and patterns, my guess is that some will be variants of existing components and patterns and some will be new components and patterns. Some will be in the design system community backlog and some won't. I think it's worth capturing the outcomes of the audit in the community backlog, as well as any tasks for the team in the team backlog.

**Comment by danjohnstonUX** [comment]
As part of points 2 and 3 (to review usage of, and identify overlap with the service manual) I've started an audit of professional facing services I'm aware of in Mural, so we can identify these components and begin conversations with those responsible for their implementations. The board is at  https://app.mural.co/t/nhsdigital8118/m/nhsdigital8118/1627994389361/2de66660fc9692bc42b973809d543b787e1c72b9?sender=u54a1b25519e7e8ddac1b2847 and is a work in progress
