### ISSUE TITLE
EPIC: Content community backlog prioritisation

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#684]
## What

The community backlog for the design system working group and content style council needs to be prioritised.

## Why

This exercise needs to be done so that the service manual team and community know the order of items of work that will deliver the most value to the community. 

## Must

- [x] [Plan GitHub content prioritisation exercise #749](https://github.com/nhsuk/nhsuk-service-manual/issues/749)
- [x] [Rationalise GitHub content issue backlog #748](https://github.com/nhsuk/nhsuk-service-manual/issues/748)
- [x] Run workshop with Content Style Council

## Could
