### ISSUE TITLE
EPIC: Community contribution

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#685]
## What

Look at how we can enable community contributions for the service manual.

## Why

For the service manual to grow and develop to meet its users' needs and maintain consistent, usable NHS products and services, we need teams to raise and discuss issues they face and tell us how things test with users.

Without regular contributions, the service manual will ultimately fail.

### Project kickoff

- [x] [Project kick-off workshop](https://github.com/nhsuk/nhsuk-service-manual/issues/706)

### User research

- [x] [Plan user research activities based on outcomes of the project kick-off workshop](https://github.com/nhsuk/nhsuk-service-manual/issues/708)
- [x] [Complete desk research into online communities, collaboration and contributions](https://github.com/nhsuk/nhsuk-service-manual/issues/709)
#### Survey
- [x] [Plan and distribute community contribution survey](https://github.com/nhsuk/nhsuk-service-manual/issues/718)
- [x] [Analyse community contribution survey responses](https://github.com/nhsuk/nhsuk-service-manual/issues/772)
- [x] [Present survey analysis to the team](https://github.com/nhsuk/nhsuk-service-manual/issues/783)

#### Interviews
- [x] [Plan community contribution user interviews](https://github.com/nhsuk/nhsuk-service-manual/issues/717)
- [x] [Run community contribution user interviews](https://github.com/nhsuk/nhsuk-service-manual/issues/770)
- [x] [Analyse community contribution user interviews](https://github.com/nhsuk/nhsuk-service-manual/issues/771)
- [x] [Present community contribution user interviews analysis](https://github.com/nhsuk/nhsuk-service-manual/issues/782)

#### Usability testing
- [x] [Plan community contribution usability test](https://github.com/nhsuk/nhsuk-service-manual/issues/719)

------

#### Sense making
- [x] [Synthesise research findings into actionable artefacts pt 1 [Persona/Behaviour archetype]](https://github.com/nhsuk/nhsuk-service-manual/issues/840)
- [x] [Synthesise research findings into actionable artefacts pt 2 [Journey map]](https://github.com/nhsuk/nhsuk-service-manual/issues/848)
#### Problem statements
- [x] [Generate problem statements & how might we (HMW)](https://github.com/nhsuk/nhsuk-service-manual/issues/841)
- [x] [Prioritise all the HMW by effort/impact](https://github.com/nhsuk/nhsuk-service-manual/issues/842)
##### Do it now HMW
- [x] [Brainstorm session to generate ideas against HMW](https://github.com/nhsuk/nhsuk-service-manual/issues/843)
- [x] [Brainstorm session to generate ideas against HMW pt II](https://github.com/nhsuk/nhsuk-service-manual/issues/929)
- [x] [Matrix & Measurements of top ideas to test against HMW pt I](https://github.com/nhsuk/nhsuk-service-manual/issues/946)
- [x] [Map out current contribution guidance on the service manual / GitHub repos](https://github.com/nhsuk/nhsuk-service-manual/issues/774)
- [x] [Research & review contribution guidance from other design systems](https://github.com/nhsuk/nhsuk-service-manual/issues/775)

-----

**Comment by Tosin-Balogun** [comment]
@davidhunter08 - Does the task here need updating to reflect where we are?

Progress - `The user research is complete, now to make those into meaningful information for further action`

**Comment by Tosin-Balogun** [comment]
Updated the 'design' section of the epic @davidhunter08

**Comment by Tosin-Balogun** [comment]
- The write up for the user behaviour is done and was played back to the team today 17-Dec-2020
- See presentation slide here -> [Contribition behaviour archetype II.pptx](https://github.com/nhsuk/nhsuk-service-manual/files/5710935/Contribition.behaviour.archetype.II.pptx)
- Next up: #848 Journey map of all behaviour types

**Comment by Tosin-Balogun** [comment]
@lucyha - Should we continue to use this Epic or do we create a new one to track things

**Comment by lucyha** [comment]
@Tosin-Balogun we can discuss at our meeting later today but I think we'll need to set-up a new epic
