### ISSUE TITLE
EPIC: Reboot Content Style Council

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#687]
## What

After six months of the team working on other coronavirus projects we are going to reboot the content style council.

## Why

Because this work has been on hold during the coronavirus pandemic and we need to reengage with the content community.

## Must

- [x] [Plan the dates and activities for style council for remainder of 2020](https://github.com/nhsuk/nhsuk-service-manual/issues/712)
- [x] [Agree on support for Sara with the meetings](https://github.com/nhsuk/nhsuk-service-manual/issues/713)
- [x] [Prepare for 4 November Style Council meeting](https://github.com/nhsuk/nhsuk-service-manual/issues/747)
- [x] [Plan GitHub content backlog prioritisation exercise #749](https://github.com/nhsuk/nhsuk-service-manual/issues/749)
- [x] [Rationalise GitHub content issue backlog #748](https://github.com/nhsuk/nhsuk-service-manual/issues/748)
- [x] [Hold 4 November Style Council meeting #833](https://github.com/nhsuk/nhsuk-service-manual/issues/833)
- [x] [Take follow up actions/publish#766](https://github.com/nhsuk/nhsuk-service-manual/issues/766)
- [x] [Run GitHub content backlog prioritisation exercise #773](https://github.com/nhsuk/nhsuk-service-manual/issues/773)
- [x] [Prepare for 9 December Style Council meeting](https://github.com/nhsuk/nhsuk-service-manual/issues/765)
- [x] [Hold December Style Council meeting](https://github.com/nhsuk/nhsuk-service-manual/issues/833)
- [x] [Take follow up actions/publish](https://github.com/nhsuk/nhsuk-service-manual/issues/795)
- [x] [Set up a team of content designers to support contribution and content Style Council #746](https://github.com/nhsuk/nhsuk-service-manual/issues/746)
- [x] [Hold meeting with core content style team to agree roles and responsibilities/rota](https://github.com/nhsuk/nhsuk-service-manual/issues/796)
