### ISSUE TITLE
EPIC: Improving Search on the service manual

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#700]
## What
Improving search on the service manual

## Why
We launched search early 2020 but were aware that there were some issues outstanding.

## Related issues
- [ ]  [Stop inappropriate H3s surfacing in search results #744](https://github.com/nhsuk/nhsuk-service-manual/issues/744)
- [x] [Search results issue - X-ray and radios page #742](https://github.com/nhsuk/nhsuk-service-manual/issues/742)
- [ ]  [Search based on "or" rather than "and" #741](https://github.com/nhsuk/nhsuk-service-manual/issues/741)
- [ ]  [Service manual search - results depend on number of letters you type in #740](https://github.com/nhsuk/nhsuk-service-manual/issues/740)
- [ ]  [Certain synonyms for search don't work #739](https://github.com/nhsuk/nhsuk-service-manual/issues/739)

**Comment by DomBaker** [comment]
We have looked at this in depth and we seem to be at a point where if we manipulate the search any further we could make it worse than it currently is. @truecroft2  has updated the search so that it can handle words such as X-Ray. But I believe this is as far as we can go without investing in a paid-for search solution.
