### ISSUE TITLE
EPIC: Service manual engagement strategy

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#710]
## What

The service manual needs to identify and create a strategy for engaging with stakeholders and the general comms strategy.

## Why

So we can effectively communicate with our users through various comms channels and we can work efficiently with our stakeholders.

## Tasks

- [x] [Stakeholder mapping workshop](https://github.com/nhsuk/nhsuk-service-manual/issues/707)
- [x] [Stakeholder engagement strategy](https://github.com/nhsuk/nhsuk-service-manual/issues/780)
- [x] [Create stakeholder communication strategy document](https://github.com/nhsuk/service-manual-internal/issues/27)

## Outcome

A finalised comms plan has been agreed for 2021.
A document listing the how we will engage with our stakeholders.
