### ISSUE TITLE
Update or remove Readability tool page and link to SMOG calculator

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#725]
### What
There's a proposal that we update this page with a link to another (probably US-based) SMOG calculator and explain add 5 years for UK.
https://service-manual.nhs.uk/content/health-literacy/use-a-readability-tool-to-prioritise-content

### Why
The readability tools page links to a SMOG calculator that's been retired. We could link to another tool. 

### Tasks
- [x] Consult Gill Rowlands, the literacy expert we worked with on the page
- [x] Consider building a tool ourselves
- [x] [Hide page for now #857](https://github.com/nhsuk/nhsuk-service-manual/issues/867)
- [x] Consider retiring the page - at January Style Council meeting
- [ ] Update or retire the page
- [x] Consider ["reading age"](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/258) at the same time
- [x] Delete PIF link on health literacy page and redirect Learning and Work Institute link to: If it helps, the readability guide is now at https://learningandwork.org.uk/resources/research-and-reports/readability-how-to-produce-clear-written-materials-for-a-range-of-readers/ -

**Comment by lucyha** [comment]
Page drafted. https://github.com/nhsuk/nhsuk-service-manual/pull/646

ON HOLD - pending review by Gill Rowlands.

**Comment by sarawilcox** [comment]
I'm putting this back into next sprint. We may need to take it to December Style Council meeting. https://github.com/nhsuk/nhsuk-service-manual/issues/765

**Comment by sarawilcox** [comment]
We may have to hold it over till January Style Council as we have some more pressing issues.

**Comment by sarawilcox** [comment]
We need to either remove the link or remove the page.

I've put a post in the NHS.UK content Slack channel, proposing to remove the page, but then to visit the issue properly at the January or February Style Council meeting.

If content designers (esp Mark Robinson, who wrote the page) agree, I think that I will still need clinician approval to take down the page before doing so early next week.

**Comment by sarawilcox** [comment]
An NHS.UK colleague on Slack says that we did some recent research with people with aphasia. And some of them had reading difficulties - especially speed  - but that does not mean they had a low reading age. Some users may have levels of dyslexia - they may read and write more slowly but not have a low reading age. There are many possible issues with reading, so maybe we should frame it differently.

**Comment by sarawilcox** [comment]
We have approval from the content team to remove the page. I'll do this early next week.

**Comment by davidhunter08** [comment]
The decision has been made to hide the page until after January's Style Council meeting: https://github.com/nhsuk/nhsuk-service-manual/issues/867

**Comment by sarawilcox** [comment]
On agenda for January Style Council meeting.

**Comment by sarawilcox** [comment]
Hi @markasrobinson, we'll be talking about the readability tool page at Style Council today. 

In the meantime, it looks as if the link to the Patient Info Forum's toolkit on the health literacy page no longer works. It takes people to PIF's home page. I've tried to find the toolkit without success. I'm proposing to just remove the link. Is that OK with you?

**Comment by markasrobinson** [comment]
Yep that sounds fine @sarawilcox

**Comment by sarawilcox** [comment]
Sorry @markasrobinson, in fact, this link is broken too: Learning and Work Institute: [How to produce clear written materials for a range of readers](https://learningandwork.org.uk/wp-content/uploads/2017/03/Readability.pdf)

That means that there will just 2 working links at the bottom of the health literacy page: 
- the HEE one - which I think I'll take directly to here: https://healtheducationengland.sharepoint.com/Comms/Digital/Shared%20Documents/Forms/AllItems.aspx?id=%2FComms%2FDigital%2FShared%20Documents%2Fhee%2Enhs%2Euk%20documents%2FWebsite%20files%2FHealth%20literacy&p=true&originalPath=aHR0cHM6Ly9oZWFsdGhlZHVjYXRpb25lbmdsYW5kLnNoYXJlcG9pbnQuY29tLzpmOi9nL0NvbW1zL0RpZ2l0YWwvRXFrZ0dqZGNOaGRJdUVzLUZjb2JMM3dCcjd0THpZUW5mZzc5MFExYmxJaXlDQT9ydGltZT0yOGVwX2pQQjJFZw
- the US health literacy resource

**Comment by cjforms** [comment]
The HEE link is to a SharePoint that I don't have access to.

There is a Health Literacy programme in partnership with NHS Scotland: https://www.e-lfh.org.uk/programmes/health-literacy/

There's also a report from the National Literacy Trust about reduced life expectancy correlating with poor literacy: https://literacytrust.org.uk/research-services/research-reports/literacy-and-life-expectancy/

Which leads me to suggest adding a paragraph about health literacy being correlated with literacy (very rough first draft for you to react to): 

Someone with poor general literacy is very likely also to have poor health literacy. The two types of literacy are not the same. It's certainly possible to read fluently in general but to struggle with the specialist vocabulary of health. In the other direction someone might have learned a lot about a particular medical condition, perhaps because they have it themselves, but have poor literacy in other areas of their lives.

**Comment by sarawilcox** [comment]
Thanks @cjforms. I'll take a look at your comments about links with Mark. 

If it means rewording the page, we'll need to run that by a Style Council meeting. We are looking at how we word things around "reading age" and poor literacy skills, so I'll feed this into the discussions.

**Comment by sarawilcox** [comment]
The clinicians have approved removing the readability tools page. I had added a brief note to the health literacy page to say that we do not recommend readability tools. I have also removed 2 broken links on the health literacy page.

The issue of "reading age"/functional literacy is being taken forward separately:
- [reading age](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/258)
- [reading age] research plan(https://github.com/nhsuk/nhsuk-service-manual/issues/939)

@davidhunter08, could you help me permanently remove the readability tools page now, please?

It needs doing at the same time as we merge this PR: https://github.com/nhsuk/nhsuk-service-manual/pull/962
