### ISSUE TITLE
User test and get feedback for surfacing the community backlog

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#736]
## What

We developed a concept to surface the community backlog within the service manual. This could use the GitHub API or be hard coded into the manual and currently GOV.UK surface the community backlog too.

## Why

We should gather feedback and conduct some user testing of the concept to help support (or reject) the concept of surfacing the backlog (which we intend on delivering, if user need suggests, as part of the redesigned service manual).

## Tasks

- [ ] discussion guide
- [ ] recruitment strategy
- [ ] recruitment and scheduling
- [ ] playback and analysis
- [ ] action logging (e.g. issues for next steps and write up in Confluence)
