### ISSUE TITLE
Stop inappropriate H3s surfacing in search results

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#744]
## What

e.g searching 'accessibility' shows 'components' as a search result - but it is a H3 on the page
(In other cases, e.g. the A to Z of NHS health writing, we want to search the H3s on the page.)

## Why

To improve search on the service manual

## Tasks

- [ ] Review this issue and update the ticket Mohammed Meah
- [ ] Look into why this is occurring in the logic
- [ ] Deploy a fix to stop H3s appearing as part of search results

**Comment by DomBaker** [comment]
Trying to fix this could in turn make the search worse, it is better to supply more results that could possibly be linked.
