### ISSUE TITLE
Organise 2nd level (advanced) GitHub training for content designers

### ISSUE THREAD

**Issue by ghost** [nhsuk/nhsuk-service-manual#753]
## What
Organise more advanced GitHub training for content designers, so that they can work in the code.

## Why
Some content designers have expressed an interest in this and we need content designers who can update prototypes themselves. 

## Tasks
- [ ] Establish in more detail what training content designers want.
- [ ] Prepare training
- [ ] Carry out training
- [ ] Gather feedback for future sessions.

**Comment by sarawilcox** [comment]
I think we can close this. We also have:
- GitHub drop in sessions #1008
- GitHub training #1337
- Make GitHub 'how to' guides #997
