### ISSUE TITLE
Review custom styles on www.nhs.uk and NHS digital service manual

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#755]
## What

Review custom styles on www.nhs.uk and NHS digital service manual.

## Why

The NHS website and NHS digital service manual has a lot of custom styles on top of the core NHS.UK frontend library. Some of these styles will be hot fixes that should really be in the frontend library, but some will be new components or styles specific to these websites.

## Tasks

- [ ] Move any hotfixes into the NHS.UK frontend
- [ ] Determine if there are any common custom components and consolidate them
- [ ] Determine whether we need to add these custom components to the frontend library
- [ ] Reduce the number of custom styles within these 2 code bases

**Comment by AdamChrimes** [comment]
To do this sprint

**Comment by AdamChrimes** [comment]
NHS website custom styles

General styles (`css/components`)

- [ ] Can we remove the guides navigation?
- [ ] Can we remove the feedback banner?
- [ ] Do we need to add the video and related nav components to the frontend library?
- [ ] Refactor the Homepage styles

Shame specific (`_shame.scss`)

- [ ] Review promo styles when Card is implemented (`nhsuk-promo--mute`)
- [ ] Custom NDOP styles (`ndop-download__link`, `ndop-download__thumbnail`) - can these be removed?
- [ ] Top tasks styles (`nhsuk-top-tasks`) - speak with IA about the future of these
- [ ] Default image styling (`max-width: 100%;`) - does this need adding to frontend library?
- [ ] Image credit styles - does this need adding to frontend library?
- [ ] Review tools block spacing 
- [ ] Review App store download styles
- [ ] Review table styles (`nhsuk-table-responsive` and `table-image`)

IA specific (`_ia-beta.scss`)

- [ ] What are the next steps for the IA syles?

Print styles (`_print.scss`)
- [ ] Refactor / remove / add to frontend library
