### ISSUE TITLE
Prepare guidance for content style guide about SEO research

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#761]
## What

Prepare a brief page for content style guide about doing SEO research.

## Why

NHS.UK content designers need to know how to do SEO research in order to write good SEO-friendly content. NHS.UK recently commissioned and ran some training for NHS.UK content designers in 2019 but we haven't captured the guidance in the service manual.

## Related issues
- [Cross check information in the Content role section of the accessibility guidance with SEO guidance being provided to NHS.UK for conflicts #759](https://github.com/nhsuk/nhsuk-service-manual/issues/759)

## Tasks

- [ ] Check that this guidance is needed
- [ ] Produce brief guidance on SEO for content designers based on recent training sessions (26 and 27 February) and drawing on Confluence page, including

- page descriptions
- headings
- synonyms 
- metadata

- [ ] Take into account existing SEO guidance on Confluence: https://confluence.service.nhs.uk/display/NP/SEO+%28search+engine+optimisation%29+guidelines
- [ ] Review meds guidance
- [ ] Put to a content crit
- [ ] Run by Content Style Council
- [ ] Publish in content style guide

## Further details

Related tickets:
https://jira.service.nhs.uk/browse/SEO-86?jql=project%20%3D%20SEO%20AND%20text%20~%20guidance
https://jira.service.nhs.uk/browse/SEO-129?jql=project%20%3D%20SEO%20AND%20text%20~%20guidance

**Comment by sarawilcox** [comment]
This hasn't come up as an issue since this was opened. I suggest that we leave open issue #759 (see above) but close this down.
