### ISSUE TITLE
Azure pipeline and Akamai improvements

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#763]
## What

We need to make a few improvements to the Azure Pipelines

## Further details

- Could the pipelines be faster? Does everything need to run for each environment? eg. PRs can be deployed before test.
- How can we release smaller and more often?
- Do we need some kind of logging, reporting and monitoring?
- Can we move the service manual to http/2
- Can we enable Brotli in Akamai
- Can we get access to Akamai and have more control?
- Can we use any extra AZDO features such as App insights etc?

## Why

To make the release process easier and smoother.

## Tasks

- [ ] Exclude markdown files (.md) from triggering the pipeline (This is currently implemented but not working)
- [ ] Ability to deploy multiple pull requests
- [ ] Better feedback to GitHub and Slack when and what deployments are finished
- [ ] Add functionality to flush the cache on pages that have changed during this release (Mike did this for CMS when pages are saved)
- [ ] We need to review the cache times on Akamai, cache seems to take a while to clear (hours compared to minutes)
- [ ] We need to start cache busting the CSS and JS files (once the Akamai cache has been reviewed otherwise the HTML would clear after the CSS resulting in a blank page)
- [ ] We need to setup some monitoring and alerting

**Comment by chrimesdev** [comment]
We also need to look at setting up Splunk on the NHS digital service manual cc: @MrKeithM
