### ISSUE TITLE
Identify data requirements and sources and collect baseline statistics

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#779]
## What

Identify the data requirements and resources and collect the base statistics.

## Why

So the service manual team can record benchmark statistics on the the usage of the service manual in order for us to continue to monitor how the service manual is being used.

## Further details

For the Github contribution figures:
In the last year (per month):

- Total number of contributions
- Type of contribution (eg: commits, comments)
- Total number of contributors

Nice to know:

- Organisation of the contributor
- Job role of the contributor

Repos to include:

- NHS.UK frontend
- NHS.UK prototype kit
- NHS.UK service manual
- NHS.UK service manual backlog

## Tasks

- [x] Collate slack analytics
- [x] Collate Github anayltics
- [x] Collate google analytics
- [x] Confirm with comms team about what data they are collecting and how it can feed into our work
- [x] Collate number of teams using the service manual
