### ISSUE TITLE
Review draft URL guidance and discuss with team how and when we will do this work

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#824]
## What

@bencullimore has drafted URL guidance. (Thanks Ben.) We weren't planning on developing the URL guidance till early next year but we may be able to progress it earlier. I'm going to do an initial review and then will discuss with the team whether we may be able to make this a pre-Christmas project. 

## Tasks

- [ ] Create a separate Google doc and do an initial content review/iteration - not doing this for now
- [x] Meet with Ben, Sarah and Leigh from the IA team
- [x] Feedback to the team
- [ ] Decide in sprint planning when we expect to progress this - not doing this for now.

**Comment by bencullimore** [comment]
@sarawilcox thanks for the update. Just for clarity - what do you mean by progressing guidance? 

As URLs form a big part of the Information Architecture remit we're actively developing this - currently liaising with stakeholders to get their feedback. 

It would be good if the service manual team could work together with us on this  - perhaps discussing timescales so we can align activities?

**Comment by sarawilcox** [comment]
Absolutely. Could we perhaps arrange a chat next week, @bencullimore? It would be good to understand where you're at and how we can align things. We don't want to progress things till you're ready for us to do so.

**Comment by sarawilcox** [comment]
Meeting with Ben, Leigh and Sarah next Wednesday afternoon.

**Comment by sarawilcox** [comment]
Linked to this epic: https://github.com/nhsuk/nhsuk-service-manual/issues/667. Am closing this ticket.
