### ISSUE TITLE
Synthesise research findings into actionable artefacts pt 1 [Persona/Behaviour archetype]

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#840]
## What
We have gotten plenty of data from our series of research activities, but we need to funnel all that research data into useful information
## Why
This allows us to make sense of the data we have gathered and enables us to make informed decisions & actions
## How
We plan to use a spectrum of behaviour types based on assumptions and evidence we have observed
## Relation
Relates to #685 
## Tasks
- [x] Create behaviour archetypes
- [x] Playback with the group on behaviour types
- [x] Write up summary of behaviour types
- [ ] Playback to whole service manual team

**Comment by Tosin-Balogun** [comment]
The team has generated about 7 behaviour archetypes which are scaled based on proximity or experience of using the service manual and their degree of activities with the contribution process. The next plan is to write up the findings to play back to the service manual team

**Comment by Tosin-Balogun** [comment]
- The write up for the user behaviour is done and was played back to the team today 17-Dec-2020
- See presentation slide here -> [Contribition behaviour archetype II.pptx](https://github.com/nhsuk/nhsuk-service-manual/files/5710935/Contribition.behaviour.archetype.II.pptx)
- Next up: #848 Journey map of all behaviour types

**Comment by Tosin-Balogun** [comment]
<img width="5165" alt="Contris 2021-01-27 18_10_05" src="https://user-images.githubusercontent.com/71393402/106161307-b8416880-617e-11eb-886f-e7e07fb41253.png">
