### ISSUE TITLE
Get the site map page on the NHS and service manual sites changed

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#873]
## What
At the December Style Council meeting, we agreed to split the word "sitemap" into 2: "site map". I can change the Wagtail page but Bal suggests that I check with Rob Sinclair about changing the footer.

## Why
This takes into account user feedback and testing on assistive tech. More details in [the site map issue](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/274). 

We need to change the NHS website to bring it into line with the change to the content style guide. 

## Tasks
- [x] Establish what impact the change might have and what action is needed
- [x] Change the Wagtail page - Sara - with new slug - unpublish and republish
- [x] Set up temporary redirect in Wagtail
- [x] Arrange with infra for a redirect
- [x] Check API works and it ripples out across the site
- [x] Change service manual site too

**Comment by sarawilcox** [comment]
@AdamChrimes Do you have any insight into how this works?

**Comment by sarawilcox** [comment]
Updated site map page in service manual. Don't think it's worth adding to What's new in its own right. I'll add it when we mention January Style Council changes.

**Comment by sarawilcox** [comment]
PR here: https://github.com/nhsuk/nhsuk-service-manual/pull/961
