### ISSUE TITLE
EPIC: Implement service manual engagement strategy

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#878]
## What

After spending time during Q3 20/21 researching and planning for our service manual engagement strategy, product, delivery and the rest of the team need to implement and carry out the actions.

## Why

So we can effectively communicate with our users through various comms channels and we can work efficiently with our stakeholders.

## Tasks

- [x] [Meeting to review the stakeholder confluence table](https://github.com/nhsuk/service-manual-internal/issues/49)
- [x] [Arrange initial meeting with NHS X Digital Transformation Team](https://github.com/nhsuk/service-manual-internal/issues/35)
- [x] [Meeting with NHS X Digital Transformation Team](https://github.com/nhsuk/service-manual-internal/issues/8)
- [x] [Draft template for monthly reporting](https://github.com/nhsuk/service-manual-internal/issues/56)
- [x] [Create January (+Q3) report](https://github.com/nhsuk/service-manual-internal/issues/57)
- [x] [Set up monthly update email for stakeholders](https://github.com/nhsuk/service-manual-internal/issues/39)

## Related to

[#710](https://github.com/nhsuk/nhsuk-service-manual/issues/710)
