### ISSUE TITLE
EPIC: Rewrite care card component as a pattern

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#880]
## What

Rewrite the care card component a design pattern.

## Why

The care card component was designed to solve a particular problem in the context of health information on the NHS website but the component been used in a wide range of other contexts with mixed results.

We believe that rewriting the component as a pattern will give clearer context as to what problem is being solved, resulting in the pattern being implemented as intended.

## To do

- [x] [Review current guidance, usage and write proposal](https://github.com/nhsuk/nhsuk-service-manual/issues/948)
- [x] [Review code, identify dependencies and propose new implementation](https://github.com/nhsuk/nhsuk-service-manual/issues/950)
- [x] [Draft guidance](https://github.com/nhsuk/nhsuk-service-manual/issues/988)
- [x] [Update guidance on the service manual](https://github.com/nhsuk/nhsuk-service-manual/issues/1176)
- [x] @sarawilcox to review 
- [x] Update code in frontend
- [x] Run past DSWG
- [x] [Iterate after DSWG](https://github.com/nhsuk/nhsuk-service-manual/issues/1500)
- [x] Publish guidance

**Comment by georginaplatt** [comment]
Am I right in thinking this EPIC is now complete? @sarawilcox @henocookie or will it be complete after #1602 ?

**Comment by henocookie** [comment]
Almost @georginaplatt we'll be releasing the update likely on Monday 😀

**Comment by sarawilcox** [comment]
Yes, I think we can keep #1602 as a separate thing, a business as usual one. It's about monitoring how things go. It ties in with some of the other issues around components and patterns.
