### ISSUE TITLE
EPIC: Rewrite review date component as a pattern and refactor code

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#883]
## What

Rewrite the review date component a design pattern and refactor the code.

## Why

There isn't a need for the review date to be a component as it could be built using existing styles. 

Removing the review date component code would reduce the size of the codebase and improve performance and maintainability.

## To do

- [x] [Remove code from the frontend](https://github.com/nhsuk/nhsuk-frontend/pull/682)
- [x] [Write new pattern guidance](https://github.com/nhsuk/nhsuk-service-manual/issues/989)
- [x] [Update guidance and examples on the service manual](https://github.com/nhsuk/nhsuk-service-manual/pull/1016)
- [x] Release changes on the frontend and service manual
- [x] Tell the community about the changes

**Comment by cjforms** [comment]
I'm delighted to see this and similar removals. 

One thing to consider: including the 'built from existing styles' thing somewhere as an example?

**Comment by sarawilcox** [comment]
Hi @davidhunter08 We've done these 2 tasks, haven't we?
Release changes on the frontend and service manual
Tell the community about the changes
I've added a link to the testing task.
