### ISSUE TITLE
EPIC: "Inclusion Discovery" (title pending)

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#886]
## What

A discovery piece of research and service design thinking into inclusion within NHS Digital. We will be focussing on inclusion activities that can be assisted or enhanced by the service manual.

## Why

There are a wide range of inclusion and diversity activities happening across NHS Digital. 

We believe that this discovery will help us understand where the service manual can be involved. This may be through compiling and writing guidance or understand how different groups are being digitally excluded. 

### Project kick off
- [x] #887 Write high level plan
- [x] #888 Write problem statements
- [x] #889 Organise meetings with stakeholders, teams and external experts
- [x] #890 Complete desk research and compile themes

### Next
