### ISSUE TITLE
 Review links to GDS guidance from our accessibility guidance

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#916]
## What

We need to review the links to GDS accessibility guidance from the NHS digital service manual accessibility guidance.

## Why

To ensure that the external links from the NHS digital service manual accessibility guidance are still suitable and relevant in case GDS has made any updates to their gudiance.

## Tasks

- [ ] Review all links
- [ ] Speak with Alistair regarding any new updates to the GDS accessibility guidance that we could link to from the NHS digital service manual
- [ ] Create an issue for any links that need updating

**Comment by sarawilcox** [comment]
Related EPIC: [Improve internal linking in service manual #689](https://github.com/nhsuk/nhsuk-service-manual/issues/689)

**Comment by lucyha** [comment]
Please see issue https://github.com/nhsuk/service-manual-internal/issues/60
