### ISSUE TITLE
Chats about commissioning and prioritisation

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual#921]
## What

Understand how work is commissioned / prioritised, and what role inclusion plays in that.

## Why

So we uncover potential issues to inform the discovery.

## Tasks

- [x] Book chat with Mohammed, Adrian, Lucy.
- [x] Have the chat.
- [x] Decide if we need to talk to anyone else for now.
