### ISSUE TITLE
Look at ratings and reviews

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual#923]
## What

The ratings and reviews team can have a look at their database to see if there's feedback that's relevant.

## Why

To inform the inclusion discovery.

## Tasks

- [x] Chat with Jack Ruck
- [x] List search terms
- [x] Get data back
- [x] Analyse the data

**Comment by ericlamarca** [comment]
We've come up with a list and shared it with Jack. Now waiting to get the data back.

**Comment by henocookie** [comment]
There's still a lot of the ratings and reviews data to analyse in time between meetings and other work, so we have agreed to continue with this in the next sprint (sprint 9)
