### ISSUE TITLE
Content and screen readers research - follow up meeting 

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#924]
## What

Follow up conversation about the content issues and accessibility that we discussed with Alistair Duggin: https://github.com/nhsuk/nhsuk-service-manual/issues/911

Including: 

- [components and headings](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/301)
- the [inset text issue](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/18)
- the [pronunciation issue](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/298)
- [hint text](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/17)
- [hyphens or spaces](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/206)

## Tasks

- [x] Arrange meeting with @mcheung-nhs, @davidhunter08 and @KarinMochan 
- [x] Review notes and recording for the above issues
- [x] Decide what action to take in each case - might include some user research, talking with cross-gov accessibility group, charities like RNIB, or on Twitter (with Alistair's help)

## Next steps
- Take action/research
- Amend components/patterns/guidance
- Feedback any learning to GOV.UK

**Comment by sarawilcox** [comment]
I've written up notes from our meeting with Alistair Duggin and decisions taken at today's follow up meeting on the 5 issues above.

**Comment by sarawilcox** [comment]
### Next steps
- @sarawilcox to make sure we have examples of the 4 issues we're taking forward so that we can test them with screen readers users (not the pronunciation issue)
- @davidhunter08 and @mcheung-nhs to prep prototypes for testing

**Comment by sarawilcox** [comment]
I think we can move this to closed. I've made notes on the 4 issues we're taking forward and set up issues for next steps.
