### ISSUE TITLE
EPIC: Design system backlog prioritisation exercise

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#951]
## What

Run a [design system backlog](https://github.com/nhsuk/nhsuk-service-manual-backlog/projects/1) prioritisation exercise with the NHS Digital user centred design community.

## Why

We need to know where to focus our efforts as a community.

## When

Every 6 months

## Where

TBC

## How

Workshop and/or online form.

Session notes and outcomes to be documented in the GitHub community backlog.

## Desired outcomes

1. A shared understanding amongst the community of the items in the backlog
2. A prioritised ‘To do’ list of of design components and patterns
3. An increase in contribution to the community backlog

### Discover

- [x] [Speak to Sara about content style guide backlog prioritisation exercise](https://github.com/nhsuk/nhsuk-service-manual/issues/1128)
- [x] [Speak to product owners / delivery managers at NHS Digital](https://github.com/nhsuk/nhsuk-service-manual/issues/1129)
- [x] [Research prioritisation methods and tools](https://github.com/nhsuk/nhsuk-service-manual/issues/1134)
- [x] [Speak to users of the design system](https://github.com/nhsuk/nhsuk-service-manual/issues/1135)
- [x] Speak to GOV.UK Design System team (Imran)
- [x] Review findings from community contribution research
- [x] [Document and share findings](https://github.com/nhsuk/nhsuk-service-manual/issues/1223)

### Plan / prepare

- [x] [Use findings from 'discover' to create and test a proof of concept](https://github.com/nhsuk/nhsuk-service-manual/issues/1211)
- [x] [Review and prep the backlog items](https://github.com/nhsuk/nhsuk-service-manual/issues/1137)
- [x] [Plan the session (set date, agenda etc)](https://github.com/nhsuk/nhsuk-service-manual/issues/957)

### Deliver

- [x] Facilitate backlog prioritisation exercise
- [x] Write-up and share outcomes and next steps
- [x] #1621
- [x] #1622

**Comment by davidhunter08** [comment]
## Proposed dates for 2021 (Thursdays, 3-4pm)

### Community backlog prioritisation exercise

- 1st April

### Design system meet-up

- 29th April 
- 27th May
- 24th June
- 22nd July 
- 26th August

### Community backlog prioritisation exercise

- 23rd September

### Design system meet-up

- 21st October
- 18th November
- 16th December (Christmas special)

**Comment by davidhunter08** [comment]
Possible criteria for prioritising:

Impact “How many designers/teams need this thing?”
v
Effort “How ready is this thing?”

**Comment by davidhunter08** [comment]
## Design system backlog prioritisation (with the community)

Some early thoughts on how we could structure the sessions.

### Session 1: Backlog introduction

#### Purpose

1. Have the community understand the purpose and benefits of the backlog
2. Get the community familiar with the backlog and backlog items
3. Gather evidence for the backlog items
4. Identify what's missing from the backlog 

#### Agenda

- Introduction
    - What is the backlog and why do we have it
    - A quick tour of the backlog
- Exercise
    - Create a GitHub account (if you’ve not got one already)
    - Add evidence to any backlog items (eg: screenshots, key findings, links to pages)
    - Create issues for any components or patterns that you think are missing (playback newly created issues to the group)
    - Feedback / questions
- Next steps

### Session 2: Prioritisation exercise

#### Purpose

1. Prioritise the backlog (based on the needs of the community)

#### Agenda

TBD

### Session 3: Prioritisation exercise playback

#### Purpose

1. Playback results of the prioritisation exercise to the community
2. Encourage contribution

#### Agenda

TBD

**Comment by henocookie** [comment]
@karlgoldstraw is this something you could have a key focus on to create handover notes or schedule some time with me, @ambchang @danjohnstonUX and @sarawilcox so we know what work has happened and what might still be needed to be done?

**Comment by sarawilcox** [comment]
Yes please, it would be good to have a record of how you went about it (with links) in case we want to run the exercise again.

**Comment by georginaplatt** [comment]
Confluence notes on the exercise: - [Community prioritisation exercise](https://nhsd-confluence.digital.nhs.uk/display/SMDS/Community+prioritisation+exercise)
