### ISSUE TITLE
Collect examples of content scenarios for screen reader testing

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#953]
## What

Following on from these issues: 
- [Content and screen readers research - initial meeting with Alistair Duggin #911](https://github.com/nhsuk/nhsuk-service-manual/issues/911)
- [Content and screen readers research - follow up meeting #924](https://github.com/nhsuk/nhsuk-service-manual/issues/924)

Make sure that we have sufficient examples of content scenarios to prep prototypes for testing for these 4 issues:
- [x] [components and headings](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/301)
- [x] the [inset text issue](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/18)
- [x] [hint text](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/17)
- [x] [hyphens or spaces](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/206)

**Comment by sarawilcox** [comment]
Sara to check for any more content examples. Note conversation about en-dashes/hyphens etc: https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/206
