### ISSUE TITLE
EPIC: Community contribution pt II

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#983]
## What

Look at how we can enable community contributions for the service manual.

## Why

For the service manual to grow and develop to meet its users' needs and maintain consistent, usable NHS products and services, we need teams to raise and discuss issues they face and tell us how things test with users.

Without regular contributions, the service manual will ultimately fail.

##### Do it next HMW
- [ ] [Brainstorm session to generate ideas against HMW pt III](https://github.com/nhsuk/nhsuk-service-manual/issues/944)
- [ ] [Brainstorm session to generate ideas against HMW pt IV](https://github.com/nhsuk/nhsuk-service-manual/issues/945)
- [ ] Matrix & Measurements of top ideas to test against HMW pt II

##### Do it later HMW
- [ ] [Brainstorm session to generate ideas against HMW pt V]( )
- [ ] [Brainstorm session to generate ideas against HMW pt VI]( )
- [ ] Matrix & Measurements of top ideas to test against HMW pt III

-----

### Measure success
- [ ] Baseline GitHub contribution figures - to help us measure success

**Comment by Tosin-Balogun** [comment]
@davidhunter08 - I have boxed off the follow up 'HMW' into this epic to be picked up later on. It would be great to do this with the community as a co-design brainstorm session
