### ISSUE TITLE
Brainstorm session to generate ideas against HMW pt V

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#984]
## What
A session to generate potential solution ideas to test against our how might we questions for sections of HMW in the 'Do it later' column

-----
## Why
We need to allow creative input from members of the team to feed into what our solutions can be, this allows for better ideas to bubble to surface and merge together. 

#### Items in 'Do it next' section
- HMW make it possible to contribute in private as well as public
- HMW make our contribution documents easy to access

-----
## Task List
- [ ] Plan session to allow for creation of ideas
- [ ] Send out invites
- [ ] Facilitate session
- [ ] Write up summary

## Related
#685 #983
