### ISSUE TITLE
Hypothesis: Enhance GitHub UX

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#991]
# What
We have completed the first part of enabling our community to easily contribute to the service manual. The outcomes from our original EPIC #685 was a series of hypothesis we need to action and test. 
These are broken into enhancing the user experience of using github, making some changes to our website and making a series of community engagement efforts.

This particular cluster of hypotheses focuses on improving the user experience of navigating and using our GitHub contribution space.

# Why
A lot of our users have indicated to github being a blocker for them being able to contribute, we believe if we make some changes, then our users would find it easy to use and thus increase the amount & quality of contributions we get

# List
- [ ] Hypothesis: Add github labels for urgent/important items
- [ ] Hypothesis: Create new issue templates by contribution type
- [ ] Hypothesis: Make github 'how to' guides
- [ ] Hypothesis: Make design system test site
- [ ] Hypothesis: Make default view for urgent/important issues

**Comment by davidhunter08** [comment]
See guidance on '[How the service manual team uses GitHub](https://github.com/nhsuk/nhsuk-service-manual/issues/1078)'
