### ISSUE TITLE
Improve Service Manual website contribution user experience

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#993]
# What
We have completed the first part of enabling our community to easily contribute to the service manual. The outcomes from our original EPIC #685 was a series of hypothesis we need to action and test. 
These are broken into enhancing the user experience of using github, making some changes to our website and making a series of community engagement efforts.

This particular cluster of hypotheses focuses on improving the discovery, navigation and engagement with our contribution process via the Service Manual website channels

# Why
Our research showed that the Service Manual website provides few indicators prompting, encouraging or directing users to the contribution mechanism. We believe if we make some changes, then our users would easily discover where & how to contribute which in turn would increase the quantity & quality of contributions we get.

# List
- [ ] Hypothesis: Add links to contribution in context
- [ ] Hypothesis: Add share buttons
- [ ] Hypothesis: Change tone to be encouraging
- [ ] Hypothesis: Change nav header to 'contribution'
- [ ] Hypothesis: Explain contribution types & how
