### ISSUE TITLE
Community engagement, training & comms

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#994]
# What
We have completed the first part of enabling our community to easily contribute to the service manual. The outcomes from our original EPIC #685 was a series of hypothesis we need to action and test. 
These are broken into enhancing the user experience of using github, making some changes to our website and making a series of community engagement efforts.

This particular cluster of hypotheses focuses on engaging with our community across multiple channels and means

# Why
Our research showed that users needed guidance & encouragement to motivate them to contribute. We believe if we tried the hypothesis listed below, then our users would become enthused, engaged & encouraged to contribute

# List
- [ ] Hypothesis: Make contribution guest blogs
- [ ] Hypothesis: Show gratitudes
- [ ] Hypothesis: Contribution as career development
- [ ] Hypothesis: GitHub drop-in sessions
- [ ] Hypothesis: Show contribution insight & impact
- [ ] Hypothesis: Spot light contributors
